//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangenta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentItemsFolder {
            get {
                return ((string)(this["RecentItemsFolder"]));
            }
            set {
                this["RecentItemsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 255, 220")]
        public global::System.Drawing.Color ColorDraft {
            get {
                return ((global::System.Drawing.Color)(this["ColorDraft"]));
            }
            set {
                this["ColorDraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 200, 200")]
        public global::System.Drawing.Color ColorStorno {
            get {
                return ((global::System.Drawing.Color)(this["ColorStorno"]));
            }
            set {
                this["ColorStorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DURS_output_folder {
            get {
                return ((string)(this["DURS_output_folder"]));
            }
            set {
                this["DURS_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XML_output_folder {
            get {
                return ((string)(this["XML_output_folder"]));
            }
            set {
                this["XML_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPAL_VOD_XSD_shema {
            get {
                return ((string)(this["OPAL_VOD_XSD_shema"]));
            }
            set {
                this["OPAL_VOD_XSD_shema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1090")]
        public int Konto_Price_with_tax_cash {
            get {
                return ((int)(this["Konto_Price_with_tax_cash"]));
            }
            set {
                this["Konto_Price_with_tax_cash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7600")]
        public int Konto_Net_price {
            get {
                return ((int)(this["Konto_Net_price"]));
            }
            set {
                this["Konto_Net_price"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26001")]
        public int Konto_VAT_rate_ganeral {
            get {
                return ((int)(this["Konto_VAT_rate_ganeral"]));
            }
            set {
                this["Konto_VAT_rate_ganeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int End_Customers_Code {
            get {
                return ((int)(this["End_Customers_Code"]));
            }
            set {
                this["End_Customers_Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Končni kupec")]
        public string End_Customers_Name {
            get {
                return ((string)(this["End_Customers_Name"]));
            }
            set {
                this["End_Customers_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1659")]
        public int Konto_Price_with_tax_payment_cards {
            get {
                return ((int)(this["Konto_Price_with_tax_payment_cards"]));
            }
            set {
                this["Konto_Price_with_tax_payment_cards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocProformaInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceForeGround"]));
            }
            set {
                this["Color_DocProformaInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowToEditLanguageText {
            get {
                return ((bool)(this["AllowToEditLanguageText"]));
            }
            set {
                this["AllowToEditLanguageText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBType {
            get {
                return ((string)(this["DBType"]));
            }
            set {
                this["DBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FinancialYear {
            get {
                return ((int)(this["FinancialYear"]));
            }
            set {
                this["FinancialYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsMode {
            get {
                return ((string)(this["eShopsMode"]));
            }
            set {
                this["eShopsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsInUse {
            get {
                return ((string)(this["eShopsInUse"]));
            }
            set {
                this["eShopsInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 220")]
        public global::System.Drawing.Color ColorFurs_InvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_InvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_InvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepPink")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceNotConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceNotConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceNotConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shops&InvoiceTable")]
        public string eManagerMode {
            get {
                return ((string)(this["eManagerMode"]));
            }
            set {
                this["eManagerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InvoiceHeaderChecked {
            get {
                return ((bool)(this["InvoiceHeaderChecked"]));
            }
            set {
                this["InvoiceHeaderChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitContainerDistanceUserSettings {
            get {
                return ((string)(this["SplitContainerDistanceUserSettings"]));
            }
            set {
                this["SplitContainerDistanceUserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LanguageID {
            get {
                return ((int)(this["LanguageID"]));
            }
            set {
                this["LanguageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Current_DocInvoice_ID {
            get {
                return ((string)(this["Current_DocInvoice_ID"]));
            }
            set {
                this["Current_DocInvoice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Current_DocProformaInvoice_ID {
            get {
                return ((string)(this["Current_DocProformaInvoice_ID"]));
            }
            set {
                this["Current_DocProformaInvoice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDocInvoiceType {
            get {
                return ((string)(this["LastDocInvoiceType"]));
            }
            set {
                this["LastDocInvoiceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyOrgID {
            get {
                return ((string)(this["MyOrgID"]));
            }
            set {
                this["MyOrgID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticSelectionOfItemFromStock {
            get {
                return ((bool)(this["AutomaticSelectionOfItemFromStock"]));
            }
            set {
                this["AutomaticSelectionOfItemFromStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 255, 186")]
        public global::System.Drawing.Color Color_DocInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceBackGround"]));
            }
            set {
                this["Color_DocInvoiceBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure")]
        public global::System.Drawing.Color Color_DocProformaInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceBackGround"]));
            }
            set {
                this["Color_DocProformaInvoiceBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SQLiteBackupFolder {
            get {
                return ((string)(this["SQLiteBackupFolder"]));
            }
            set {
                this["SQLiteBackupFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Startup_TangentaAbout_Showed {
            get {
                return ((bool)(this["Startup_TangentaAbout_Showed"]));
            }
            set {
                this["Startup_TangentaAbout_Showed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Startup_TangentaLicence_Showed {
            get {
                return ((bool)(this["Startup_TangentaLicence_Showed"]));
            }
            set {
                this["Startup_TangentaLicence_Showed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HelpLocalPath {
            get {
                return ((string)(this["HelpLocalPath"]));
            }
            set {
                this["HelpLocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dstrucl.github.io/Tangenta-Help/")]
        public string HelpRemoteURL {
            get {
                return ((string)(this["HelpRemoteURL"]));
            }
            set {
                this["HelpRemoteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceForeGround"]));
            }
            set {
                this["Color_DocInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstallationFinished {
            get {
                return ((bool)(this["InstallationFinished"]));
            }
            set {
                this["InstallationFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Current_DataBase {
            get {
                return ((string)(this["Current_DataBase"]));
            }
            set {
                this["Current_DataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopC_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopC_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopC_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopC_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopC_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopC_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopB_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopB_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopB_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopB_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopB_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopB_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentMan_SplitControl1_splitterdistance {
            get {
                return ((int)(this["DocumentMan_SplitControl1_splitterdistance"]));
            }
            set {
                this["DocumentMan_SplitControl1_splitterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopA_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopA_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_Editor_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopA_Editor_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopA_Editor_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_Editor_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopA_Editor_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopA_Editor_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl1_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl1_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl2_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl2_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl3_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl3_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl3_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_WindowState {
            get {
                return ((int)(this["Form_Document_WindowState"]));
            }
            set {
                this["Form_Document_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Left {
            get {
                return ((int)(this["Form_Document_Left"]));
            }
            set {
                this["Form_Document_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Top {
            get {
                return ((int)(this["Form_Document_Top"]));
            }
            set {
                this["Form_Document_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Width {
            get {
                return ((int)(this["Form_Document_Width"]));
            }
            set {
                this["Form_Document_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Height {
            get {
                return ((int)(this["Form_Document_Height"]));
            }
            set {
                this["Form_Document_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Office_ID {
            get {
                return ((string)(this["Office_ID"]));
            }
            set {
                this["Office_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ElectronicDevice_ID {
            get {
                return ((string)(this["ElectronicDevice_ID"]));
            }
            set {
                this["ElectronicDevice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Login_MultipleUsers {
            get {
                return ((bool)(this["Login_MultipleUsers"]));
            }
            set {
                this["Login_MultipleUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ControlLayout_TouchScreen {
            get {
                return ((bool)(this["ControlLayout_TouchScreen"]));
            }
            set {
                this["ControlLayout_TouchScreen"] = value;
            }
        }
    }
}
