//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangenta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class SettingsUser : global::System.Configuration.ApplicationSettingsBase {
        
        private static SettingsUser defaultInstance = ((SettingsUser)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SettingsUser())));
        
        public static SettingsUser Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InvoiceHeaderChecked {
            get {
                return ((bool)(this["InvoiceHeaderChecked"]));
            }
            set {
                this["InvoiceHeaderChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 255, 186")]
        public global::System.Drawing.Color Color_DocInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceBackGround"]));
            }
            set {
                this["Color_DocInvoiceBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocProformaInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceForeGround"]));
            }
            set {
                this["Color_DocProformaInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FinancialYear {
            get {
                return ((int)(this["FinancialYear"]));
            }
            set {
                this["FinancialYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsMode {
            get {
                return ((string)(this["eShopsMode"]));
            }
            set {
                this["eShopsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsInUse {
            get {
                return ((string)(this["eShopsInUse"]));
            }
            set {
                this["eShopsInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitContainerDistanceUserSettings {
            get {
                return ((string)(this["SplitContainerDistanceUserSettings"]));
            }
            set {
                this["SplitContainerDistanceUserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDocInvoiceType {
            get {
                return ((string)(this["LastDocInvoiceType"]));
            }
            set {
                this["LastDocInvoiceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopC_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopC_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopC_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopC_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopC_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopC_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopB_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopB_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopB_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopB_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopB_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopB_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopA_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopA_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentMan_SplitControl1_splitterdistance {
            get {
                return ((int)(this["DocumentMan_SplitControl1_splitterdistance"]));
            }
            set {
                this["DocumentMan_SplitControl1_splitterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_Editor_SplitControl1_spliterdistance {
            get {
                return ((int)(this["ShopA_Editor_SplitControl1_spliterdistance"]));
            }
            set {
                this["ShopA_Editor_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_Editor_SplitControl2_spliterdistance {
            get {
                return ((int)(this["ShopA_Editor_SplitControl2_spliterdistance"]));
            }
            set {
                this["ShopA_Editor_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int ShopA_Editor_SplitControl3_spliterdistance {
            get {
                return ((int)(this["ShopA_Editor_SplitControl3_spliterdistance"]));
            }
            set {
                this["ShopA_Editor_SplitControl3_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl1_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl1_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl1_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl2_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl2_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl2_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DocumentEditor_SplitControl3_spliterdistance {
            get {
                return ((int)(this["DocumentEditor_SplitControl3_spliterdistance"]));
            }
            set {
                this["DocumentEditor_SplitControl3_spliterdistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_WindowState {
            get {
                return ((int)(this["Form_Document_WindowState"]));
            }
            set {
                this["Form_Document_WindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Left {
            get {
                return ((int)(this["Form_Document_Left"]));
            }
            set {
                this["Form_Document_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Top {
            get {
                return ((int)(this["Form_Document_Top"]));
            }
            set {
                this["Form_Document_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Width {
            get {
                return ((int)(this["Form_Document_Width"]));
            }
            set {
                this["Form_Document_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int Form_Document_Height {
            get {
                return ((int)(this["Form_Document_Height"]));
            }
            set {
                this["Form_Document_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceForeGround"]));
            }
            set {
                this["Color_DocInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure")]
        public global::System.Drawing.Color Color_DocProformaInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceBackGround"]));
            }
            set {
                this["Color_DocProformaInvoiceBackGround"] = value;
            }
        }
    }
}
