//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangenta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentItemsFolder {
            get {
                return ((string)(this["RecentItemsFolder"]));
            }
            set {
                this["RecentItemsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\")]
        public string IniFileFolder {
            get {
                return ((string)(this["IniFileFolder"]));
            }
            set {
                this["IniFileFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ReceiptPrinter {
            get {
                return ((string)(this["ReceiptPrinter"]));
            }
            set {
                this["ReceiptPrinter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PageSettings_Landscape {
            get {
                return ((bool)(this["PageSettings_Landscape"]));
            }
            set {
                this["PageSettings_Landscape"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PageSettings_Color {
            get {
                return ((bool)(this["PageSettings_Color"]));
            }
            set {
                this["PageSettings_Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PageSettings_HardMarginX {
            get {
                return ((float)(this["PageSettings_HardMarginX"]));
            }
            set {
                this["PageSettings_HardMarginX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float PageSettings_HardMarginY {
            get {
                return ((float)(this["PageSettings_HardMarginY"]));
            }
            set {
                this["PageSettings_HardMarginY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PaperSize_Width {
            get {
                return ((int)(this["PageSettings_PaperSize_Width"]));
            }
            set {
                this["PageSettings_PaperSize_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PaperSize_Height {
            get {
                return ((int)(this["PageSettings_PaperSize_Height"]));
            }
            set {
                this["PageSettings_PaperSize_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PageSettings_PaperSize_PaperName {
            get {
                return ((string)(this["PageSettings_PaperSize_PaperName"]));
            }
            set {
                this["PageSettings_PaperSize_PaperName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PaperSize_RawKind {
            get {
                return ((int)(this["PageSettings_PaperSize_RawKind"]));
            }
            set {
                this["PageSettings_PaperSize_RawKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PaperSource_RawKind {
            get {
                return ((int)(this["PageSettings_PaperSource_RawKind"]));
            }
            set {
                this["PageSettings_PaperSource_RawKind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PageSettings_PaperSource_SourceName {
            get {
                return ((string)(this["PageSettings_PaperSource_SourceName"]));
            }
            set {
                this["PageSettings_PaperSource_SourceName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PrinterResolution_X {
            get {
                return ((int)(this["PageSettings_PrinterResolution_X"]));
            }
            set {
                this["PageSettings_PrinterResolution_X"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PrinterResolution_Y {
            get {
                return ((int)(this["PageSettings_PrinterResolution_Y"]));
            }
            set {
                this["PageSettings_PrinterResolution_Y"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PageSettings_PrinterResolution_Kind {
            get {
                return ((int)(this["PageSettings_PrinterResolution_Kind"]));
            }
            set {
                this["PageSettings_PrinterResolution_Kind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackupFolder {
            get {
                return ((string)(this["BackupFolder"]));
            }
            set {
                this["BackupFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PrintAtOnce {
            get {
                return ((bool)(this["PrintAtOnce"]));
            }
            set {
                this["PrintAtOnce"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 255, 220")]
        public global::System.Drawing.Color ColorDraft {
            get {
                return ((global::System.Drawing.Color)(this["ColorDraft"]));
            }
            set {
                this["ColorDraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 200, 200")]
        public global::System.Drawing.Color ColorStorno {
            get {
                return ((global::System.Drawing.Color)(this["ColorStorno"]));
            }
            set {
                this["ColorStorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DURS_output_folder {
            get {
                return ((string)(this["DURS_output_folder"]));
            }
            set {
                this["DURS_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XML_output_folder {
            get {
                return ((string)(this["XML_output_folder"]));
            }
            set {
                this["XML_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPAL_VOD_XSD_shema {
            get {
                return ((string)(this["OPAL_VOD_XSD_shema"]));
            }
            set {
                this["OPAL_VOD_XSD_shema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1090")]
        public int Konto_Price_with_tax_cash {
            get {
                return ((int)(this["Konto_Price_with_tax_cash"]));
            }
            set {
                this["Konto_Price_with_tax_cash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7600")]
        public int Konto_Net_price {
            get {
                return ((int)(this["Konto_Net_price"]));
            }
            set {
                this["Konto_Net_price"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26001")]
        public int Konto_VAT_rate_ganeral {
            get {
                return ((int)(this["Konto_VAT_rate_ganeral"]));
            }
            set {
                this["Konto_VAT_rate_ganeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int End_Customers_Code {
            get {
                return ((int)(this["End_Customers_Code"]));
            }
            set {
                this["End_Customers_Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Končni kupec")]
        public string End_Customers_Name {
            get {
                return ((string)(this["End_Customers_Name"]));
            }
            set {
                this["End_Customers_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1659")]
        public int Konto_Price_with_tax_payment_cards {
            get {
                return ((int)(this["Konto_Price_with_tax_payment_cards"]));
            }
            set {
                this["Konto_Price_with_tax_payment_cards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WorkingPlace_Name {
            get {
                return ((string)(this["WorkingPlace_Name"]));
            }
            set {
                this["WorkingPlace_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowToEditLanguageText {
            get {
                return ((bool)(this["AllowToEditLanguageText"]));
            }
            set {
                this["AllowToEditLanguageText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBType {
            get {
                return ((string)(this["DBType"]));
            }
            set {
                this["DBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int FinancialYear {
            get {
                return ((int)(this["FinancialYear"]));
            }
            set {
                this["FinancialYear"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blagajna1")]
        public string CasshierName {
            get {
                return ((string)(this["CasshierName"]));
            }
            set {
                this["CasshierName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsMode {
            get {
                return ((string)(this["eShopsMode"]));
            }
            set {
                this["eShopsMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsInUse {
            get {
                return ((string)(this["eShopsInUse"]));
            }
            set {
                this["eShopsInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 192")]
        public global::System.Drawing.Color ColorFurs_InvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_InvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_InvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192, 255, 255")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceNotConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceNotConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceNotConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shops&InvoiceTable")]
        public string eManagerMode {
            get {
                return ((string)(this["eManagerMode"]));
            }
            set {
                this["eManagerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InvoiceHeaderChecked {
            get {
                return ((bool)(this["InvoiceHeaderChecked"]));
            }
            set {
                this["InvoiceHeaderChecked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitContainerDistanceUserSettings {
            get {
                return ((string)(this["SplitContainerDistanceUserSettings"]));
            }
            set {
                this["SplitContainerDistanceUserSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LanguageID {
            get {
                return ((int)(this["LanguageID"]));
            }
            set {
                this["LanguageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ED1")]
        public string ElectronicDevice_ID {
            get {
                return ((string)(this["ElectronicDevice_ID"]));
            }
            set {
                this["ElectronicDevice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long Current_DocInvoice_ID {
            get {
                return ((long)(this["Current_DocInvoice_ID"]));
            }
            set {
                this["Current_DocInvoice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public long Current_DocProformaInvoice_ID {
            get {
                return ((long)(this["Current_DocProformaInvoice_ID"]));
            }
            set {
                this["Current_DocProformaInvoice_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastDocInvoiceType {
            get {
                return ((string)(this["LastDocInvoiceType"]));
            }
            set {
                this["LastDocInvoiceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyOrgID {
            get {
                return ((string)(this["MyOrgID"]));
            }
            set {
                this["MyOrgID"] = value;
            }
        }
    }
}
