//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tangenta.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RecentItemsFolder {
            get {
                return ((string)(this["RecentItemsFolder"]));
            }
            set {
                this["RecentItemsFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("220, 255, 220")]
        public global::System.Drawing.Color ColorDraft {
            get {
                return ((global::System.Drawing.Color)(this["ColorDraft"]));
            }
            set {
                this["ColorDraft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 200, 200")]
        public global::System.Drawing.Color ColorStorno {
            get {
                return ((global::System.Drawing.Color)(this["ColorStorno"]));
            }
            set {
                this["ColorStorno"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DURS_output_folder {
            get {
                return ((string)(this["DURS_output_folder"]));
            }
            set {
                this["DURS_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string XML_output_folder {
            get {
                return ((string)(this["XML_output_folder"]));
            }
            set {
                this["XML_output_folder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OPAL_VOD_XSD_shema {
            get {
                return ((string)(this["OPAL_VOD_XSD_shema"]));
            }
            set {
                this["OPAL_VOD_XSD_shema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1090")]
        public int Konto_Price_with_tax_cash {
            get {
                return ((int)(this["Konto_Price_with_tax_cash"]));
            }
            set {
                this["Konto_Price_with_tax_cash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7600")]
        public int Konto_Net_price {
            get {
                return ((int)(this["Konto_Net_price"]));
            }
            set {
                this["Konto_Net_price"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("26001")]
        public int Konto_VAT_rate_ganeral {
            get {
                return ((int)(this["Konto_VAT_rate_ganeral"]));
            }
            set {
                this["Konto_VAT_rate_ganeral"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int End_Customers_Code {
            get {
                return ((int)(this["End_Customers_Code"]));
            }
            set {
                this["End_Customers_Code"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Končni kupec")]
        public string End_Customers_Name {
            get {
                return ((string)(this["End_Customers_Name"]));
            }
            set {
                this["End_Customers_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1659")]
        public int Konto_Price_with_tax_payment_cards {
            get {
                return ((int)(this["Konto_Price_with_tax_payment_cards"]));
            }
            set {
                this["Konto_Price_with_tax_payment_cards"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowToEditLanguageText {
            get {
                return ((bool)(this["AllowToEditLanguageText"]));
            }
            set {
                this["AllowToEditLanguageText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DBType {
            get {
                return ((string)(this["DBType"]));
            }
            set {
                this["DBType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullScreen {
            get {
                return ((bool)(this["FullScreen"]));
            }
            set {
                this["FullScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 255, 220")]
        public global::System.Drawing.Color ColorFurs_InvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_InvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_InvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 224, 192")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeepPink")]
        public global::System.Drawing.Color ColorFurs_SalesBookInvoiceNotConfirmed {
            get {
                return ((global::System.Drawing.Color)(this["ColorFurs_SalesBookInvoiceNotConfirmed"]));
            }
            set {
                this["ColorFurs_SalesBookInvoiceNotConfirmed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Shops&InvoiceTable")]
        public string eManagerMode {
            get {
                return ((string)(this["eManagerMode"]));
            }
            set {
                this["eManagerMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int LanguageID {
            get {
                return ((int)(this["LanguageID"]));
            }
            set {
                this["LanguageID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutomaticSelectionOfItemFromStock {
            get {
                return ((bool)(this["AutomaticSelectionOfItemFromStock"]));
            }
            set {
                this["AutomaticSelectionOfItemFromStock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SQLiteBackupFolder {
            get {
                return ((string)(this["SQLiteBackupFolder"]));
            }
            set {
                this["SQLiteBackupFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Startup_TangentaAbout_Showed {
            get {
                return ((bool)(this["Startup_TangentaAbout_Showed"]));
            }
            set {
                this["Startup_TangentaAbout_Showed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Startup_TangentaLicence_Showed {
            get {
                return ((bool)(this["Startup_TangentaLicence_Showed"]));
            }
            set {
                this["Startup_TangentaLicence_Showed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string HelpLocalPath {
            get {
                return ((string)(this["HelpLocalPath"]));
            }
            set {
                this["HelpLocalPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://dstrucl.github.io/Tangenta-Help/")]
        public string HelpRemoteURL {
            get {
                return ((string)(this["HelpRemoteURL"]));
            }
            set {
                this["HelpRemoteURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstallationFinished {
            get {
                return ((bool)(this["InstallationFinished"]));
            }
            set {
                this["InstallationFinished"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Current_DataBase {
            get {
                return ((string)(this["Current_DataBase"]));
            }
            set {
                this["Current_DataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Login_MultipleUsers {
            get {
                return ((bool)(this["Login_MultipleUsers"]));
            }
            set {
                this["Login_MultipleUsers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ControlLayout_TouchScreen {
            get {
                return ((bool)(this["ControlLayout_TouchScreen"]));
            }
            set {
                this["ControlLayout_TouchScreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int AccessAuthentication {
            get {
                return ((int)(this["AccessAuthentication"]));
            }
            set {
                this["AccessAuthentication"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int timer_Login_MultiUser_Countdown {
            get {
                return ((int)(this["timer_Login_MultiUser_Countdown"]));
            }
            set {
                this["timer_Login_MultiUser_Countdown"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseWorkAreas {
            get {
                return ((bool)(this["UseWorkAreas"]));
            }
            set {
                this["UseWorkAreas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MyOrgID {
            get {
                return ((string)(this["MyOrgID"]));
            }
            set {
                this["MyOrgID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("226, 255, 186")]
        public global::System.Drawing.Color Color_DocInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceBackGround"]));
            }
            set {
                this["Color_DocInvoiceBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocInvoiceForeGround"]));
            }
            set {
                this["Color_DocInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Azure")]
        public global::System.Drawing.Color Color_DocProformaInvoiceBackGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceBackGround"]));
            }
            set {
                this["Color_DocProformaInvoiceBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color Color_DocProformaInvoiceForeGround {
            get {
                return ((global::System.Drawing.Color)(this["Color_DocProformaInvoiceForeGround"]));
            }
            set {
                this["Color_DocProformaInvoiceForeGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string eShopsInUse {
            get {
                return ((string)(this["eShopsInUse"]));
            }
            set {
                this["eShopsInUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAdministratorsInMultiuserLogin {
            get {
                return ((bool)(this["ShowAdministratorsInMultiuserLogin"]));
            }
            set {
                this["ShowAdministratorsInMultiuserLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdleControl_Active {
            get {
                return ((bool)(this["IdleControl_Active"]));
            }
            set {
                this["IdleControl_Active"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int IdleControl_TimeInSecondsToActivate {
            get {
                return ((int)(this["IdleControl_TimeInSecondsToActivate"]));
            }
            set {
                this["IdleControl_TimeInSecondsToActivate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IdleControl_UseExitButton {
            get {
                return ((bool)(this["IdleControl_UseExitButton"]));
            }
            set {
                this["IdleControl_UseExitButton"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IdleControl_ShowURL2 {
            get {
                return ((bool)(this["IdleControl_ShowURL2"]));
            }
            set {
                this["IdleControl_ShowURL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http:\\\\www.tangenta.si")]
        public string IdleControl_URL1 {
            get {
                return ((string)(this["IdleControl_URL1"]));
            }
            set {
                this["IdleControl_URL1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdleControl_URL2 {
            get {
                return ((string)(this["IdleControl_URL2"]));
            }
            set {
                this["IdleControl_URL2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdleControl_FileImageUrl1 {
            get {
                return ((string)(this["IdleControl_FileImageUrl1"]));
            }
            set {
                this["IdleControl_FileImageUrl1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IdleControl_FileImageUrl2 {
            get {
                return ((string)(this["IdleControl_FileImageUrl2"]));
            }
            set {
                this["IdleControl_FileImageUrl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RecordCashierActivity {
            get {
                return ((bool)(this["RecordCashierActivity"]));
            }
            set {
                this["RecordCashierActivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WaitToChangeDataBaseAtStartup {
            get {
                return ((bool)(this["WaitToChangeDataBaseAtStartup"]));
            }
            set {
                this["WaitToChangeDataBaseAtStartup"] = value;
            }
        }
    }
}
