//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Country.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Country.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ISO_4217 Pblshd=&quot;2016-02-24&quot;&gt;
        ///&lt;CcyTbl&gt;
        ///&lt;CcyNtry&gt;
        ///&lt;CtryNm&gt;AFGHANISTAN&lt;/CtryNm&gt;
        ///&lt;CcyNm&gt;Afghani&lt;/CcyNm&gt;
        ///&lt;Ccy&gt;AFN&lt;/Ccy&gt;
        ///&lt;CcyNbr&gt;971&lt;/CcyNbr&gt;
        ///&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///&lt;/CcyNtry&gt;
        ///&lt;CcyNtry&gt;
        ///&lt;CtryNm&gt;ÅLAND ISLANDS&lt;/CtryNm&gt;
        ///&lt;CcyNm&gt;Euro&lt;/CcyNm&gt;
        ///&lt;Ccy&gt;EUR&lt;/Ccy&gt;
        ///&lt;CcyNbr&gt;978&lt;/CcyNbr&gt;
        ///&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///&lt;/CcyNtry&gt;
        ///&lt;CcyNtry&gt;
        ///&lt;CtryNm&gt;ALBANIA&lt;/CtryNm&gt;
        ///&lt;CcyNm&gt;Lek&lt;/CcyNm&gt;
        ///&lt;Ccy&gt;ALL&lt;/Ccy&gt;
        ///&lt;CcyNbr&gt;008&lt;/CcyNbr&gt;
        ///&lt;CcyMnrUnts&gt;2&lt;/CcyMnrUnts&gt;
        ///&lt;/CcyNtry&gt;
        ///&lt;CcyNtry&gt;
        ///&lt;CtryNm&gt;ALGERIA&lt;/CtryNm&gt;
        ///&lt;CcyNm&gt;Algeri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ISO_4217_country_currency_table {
            get {
                return ResourceManager.GetString("ISO_4217_country_currency_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon State {
            get {
                object obj = ResourceManager.GetObject("State", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
