//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBConnectionControl_Settings.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class LocalDB4 : global::System.Configuration.ApplicationSettingsBase {
        
        private static LocalDB4 defaultInstance = ((LocalDB4)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new LocalDB4())));
        
        public static LocalDB4 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalDB_DataBaseFilePath {
            get {
                return ((string)(this["LocalDB_DataBaseFilePath"]));
            }
            set {
                this["LocalDB_DataBaseFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalDB_DataBaseFileName {
            get {
                return ((string)(this["LocalDB_DataBaseFileName"]));
            }
            set {
                this["LocalDB_DataBaseFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LocalDB_crypted_Password {
            get {
                return ((string)(this["LocalDB_crypted_Password"]));
            }
            set {
                this["LocalDB_crypted_Password"] = value;
            }
        }
    }
}
