using LanguageControl;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace TangentaSampleDB
{
    public partial class Form_Items_Samples : Form
    {
        public bool bAutoGenerateDemoSampleItems = false;
        public int iNumberOfGroupsInLevel1 = 0;
        public int iNumberOfGroupsInLevel2 = 0;
        public int iNumberOfGroupsInLevel3 = 0;
        public int iNumberOfItemsPerGroup = 0;

        NavigationButtons.Navigation nav = null;
        public Form_Items_Samples(NavigationButtons.Navigation xnav,string shopName)
        {
            InitializeComponent();
            nav = xnav;
            usrc_NavigationButtons1.Init(nav);
            lngRPMS.s_InsertSampleItems_for_shop.Text(this, shopName);
            lngRPMS.s_rdb_InsertItemsManualy.Text(rdb_InsertItemsManualy);
            lngRPMS.s_rdb_AutoGenerateDemoItems.Text(this.rdb_AutoGenerateDemoItems);
            lngRPMS.s_GeneratorOfSampleItems.Text(grp_AutoGenerateSampleItems);
            lngRPMS.s_lbl_ItemNamePrefix.Text(this.lbl_ItemPrefix);
            lngRPMS.s_lbl_ItemAbbreviationPrefix.Text(this.lbl_ItemAbbreviationPrefix);
            lngRPMS.s_lbl_Number_Of_Groups_in_Level1.Text(this.lbl_Number_Of_Groups_in_Level1);
            lngRPMS.s_lbl_Number_Of_Groups_in_Level2.Text(this.lbl_Number_Of_Groups_in_Level2);
            lngRPMS.s_lbl_Number_Of_Groups_in_Level3.Text(this.lbl_Number_Of_Groups_in_Level3);
            lngRPMS.s_lbl_Number_Of_Items_per_group.Text(this.lbl_NumberOfItemsPerGroup);
            this.txt_Item_Name_Prefix.Text = shopName+lngRPMS.s_txt_Item_Name_Prefix.s;
            this.txt_ItemAbbreviationPrefix.Text = shopName+lngRPMS.s_txt_Item_Name_AbrPrefix.s;

            rdb_InsertItemsManualy.Checked = true;

        }
        public int iNumberOffAll()
        {
            int iAll = 1;
            if (iNumberOfGroupsInLevel3 > 0)
            {
                iAll = (iNumberOfGroupsInLevel3 * iNumberOfGroupsInLevel2 * iNumberOfGroupsInLevel1) * iNumberOfItemsPerGroup
                       + (iNumberOfGroupsInLevel3 * iNumberOfGroupsInLevel2) * iNumberOfItemsPerGroup
                       + iNumberOfGroupsInLevel3 * iNumberOfItemsPerGroup
                       + iNumberOfItemsPerGroup;
            }
            else if (iNumberOfGroupsInLevel2 > 0)
            {
                iAll = (iNumberOfGroupsInLevel2 * iNumberOfGroupsInLevel1) * iNumberOfItemsPerGroup
                       + iNumberOfGroupsInLevel2 * iNumberOfItemsPerGroup
                       + iNumberOfItemsPerGroup;
            }
            else if (iNumberOfGroupsInLevel1 > 0)
            {
                iAll = (iNumberOfGroupsInLevel1) * iNumberOfItemsPerGroup
                       + iNumberOfItemsPerGroup;
            }
            else
            {
                iAll = iNumberOfItemsPerGroup;
            }
            return iAll;
        }

    private void usrc_NavigationButtons1_ButtonPressed(NavigationButtons.Navigation.eEvent evt)
        {
            nav.eExitResult = evt;
            switch (evt)
            {
                case NavigationButtons.Navigation.eEvent.NEXT:
                    iNumberOfGroupsInLevel1 = Convert.ToInt32(nm_UpDn_NumberOfGroupsInLevel1.Value);
                    iNumberOfGroupsInLevel2 = Convert.ToInt32(nm_UpDn_NumberOfGroupsInLevel2.Value);
                    iNumberOfGroupsInLevel3 = Convert.ToInt32(nm_UpDn_NumberOfGroupsInLevel3.Value);
                    iNumberOfItemsPerGroup = Convert.ToInt32(nmUpDn_NumberOfItemsPerGroup.Value);
                    bAutoGenerateDemoSampleItems = rdb_AutoGenerateDemoItems.Checked;
                    this.Close();
                    DialogResult = DialogResult.OK;
                    break;
                default:
                    this.Close();
                    DialogResult = DialogResult.Cancel;
                    break;
            }
        }

        private void nm_UpDn_NumberOfGroupsInLevel1_ValueChanged(object sender, EventArgs e)
        {
            if (nm_UpDn_NumberOfGroupsInLevel1.Value>0)
            {
                EnableLevel(2);
            }
            else
            {
                DisableLevel(2);
                DisableLevel(3);
            }
        }

        private void nm_UpDn_NumberOfGroupsInLevel2_ValueChanged(object sender, EventArgs e)
        {
            if (nm_UpDn_NumberOfGroupsInLevel2.Value > 0)
            {
                EnableLevel(3);
            }
            else
            {
                DisableLevel(3);
            }
        }

        private void DisableLevel(int v)
        {
            switch (v)
            {
                case 2:
                    nm_UpDn_NumberOfGroupsInLevel2.Enabled = false;
                    lbl_Number_Of_Groups_in_Level2.Enabled = false;
                    break;
                case 3:
                    nm_UpDn_NumberOfGroupsInLevel3.Enabled = false;
                    lbl_Number_Of_Groups_in_Level3.Enabled = false;
                    break;
            }

        }

        private void EnableLevel(int v)
        {
            switch (v)
            {
                case 2:
                    nm_UpDn_NumberOfGroupsInLevel2.Enabled = true;
                    lbl_Number_Of_Groups_in_Level2.Enabled = true;
                    break;
                case 3:
                    nm_UpDn_NumberOfGroupsInLevel3.Enabled = true;
                    lbl_Number_Of_Groups_in_Level3.Enabled = true;
                    break;
            }
        }

    }
}
