namespace TangentaSampleDB
{
    partial class Form_Items_Samples
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form_Items_Samples));
            this.rdb_InsertItemsManualy = new System.Windows.Forms.RadioButton();
            this.rdb_AutoGenerateDemoItems = new System.Windows.Forms.RadioButton();
            this.grp_AutoGenerateSampleItems = new System.Windows.Forms.GroupBox();
            this.lbl_NumberOfTitemsToBeInserted = new System.Windows.Forms.Label();
            this.lbl_NumberOfItemsPerGroup = new System.Windows.Forms.Label();
            this.nmUpDn_NumberOfItemsPerGroup = new System.Windows.Forms.NumericUpDown();
            this.lbl_Number_Of_Groups_in_Level3 = new System.Windows.Forms.Label();
            this.nm_UpDn_NumberOfGroupsInLevel3 = new System.Windows.Forms.NumericUpDown();
            this.lbl_Number_Of_Groups_in_Level2 = new System.Windows.Forms.Label();
            this.nm_UpDn_NumberOfGroupsInLevel2 = new System.Windows.Forms.NumericUpDown();
            this.lbl_Number_Of_Groups_in_Level1 = new System.Windows.Forms.Label();
            this.nm_UpDn_NumberOfGroupsInLevel1 = new System.Windows.Forms.NumericUpDown();
            this.txt_ItemAbbreviationPrefix = new System.Windows.Forms.TextBox();
            this.lbl_ItemAbbreviationPrefix = new System.Windows.Forms.Label();
            this.txt_Item_Name_Prefix = new System.Windows.Forms.TextBox();
            this.lbl_ItemPrefix = new System.Windows.Forms.Label();
            this.usrc_NavigationButtons1 = new NavigationButtons.usrc_NavigationButtons();
            this.grp_AutoGenerateSampleItems.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nmUpDn_NumberOfItemsPerGroup)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel3)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel1)).BeginInit();
            this.SuspendLayout();
            // 
            // rdb_InsertItemsManualy
            // 
            this.rdb_InsertItemsManualy.AutoSize = true;
            this.rdb_InsertItemsManualy.Location = new System.Drawing.Point(384, 12);
            this.rdb_InsertItemsManualy.Name = "rdb_InsertItemsManualy";
            this.rdb_InsertItemsManualy.Size = new System.Drawing.Size(121, 17);
            this.rdb_InsertItemsManualy.TabIndex = 1;
            this.rdb_InsertItemsManualy.TabStop = true;
            this.rdb_InsertItemsManualy.Text = "Enter Items Manualy";
            this.rdb_InsertItemsManualy.UseVisualStyleBackColor = true;
            // 
            // rdb_AutoGenerateDemoItems
            // 
            this.rdb_AutoGenerateDemoItems.AutoSize = true;
            this.rdb_AutoGenerateDemoItems.Location = new System.Drawing.Point(23, 12);
            this.rdb_AutoGenerateDemoItems.Name = "rdb_AutoGenerateDemoItems";
            this.rdb_AutoGenerateDemoItems.Size = new System.Drawing.Size(184, 17);
            this.rdb_AutoGenerateDemoItems.TabIndex = 2;
            this.rdb_AutoGenerateDemoItems.TabStop = true;
            this.rdb_AutoGenerateDemoItems.Text = "Auto generate demo sample items";
            this.rdb_AutoGenerateDemoItems.UseVisualStyleBackColor = true;
            // 
            // grp_AutoGenerateSampleItems
            // 
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_NumberOfTitemsToBeInserted);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_NumberOfItemsPerGroup);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.nmUpDn_NumberOfItemsPerGroup);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_Number_Of_Groups_in_Level3);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.nm_UpDn_NumberOfGroupsInLevel3);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_Number_Of_Groups_in_Level2);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.nm_UpDn_NumberOfGroupsInLevel2);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_Number_Of_Groups_in_Level1);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.nm_UpDn_NumberOfGroupsInLevel1);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.txt_ItemAbbreviationPrefix);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_ItemAbbreviationPrefix);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.txt_Item_Name_Prefix);
            this.grp_AutoGenerateSampleItems.Controls.Add(this.lbl_ItemPrefix);
            this.grp_AutoGenerateSampleItems.Location = new System.Drawing.Point(12, 35);
            this.grp_AutoGenerateSampleItems.Name = "grp_AutoGenerateSampleItems";
            this.grp_AutoGenerateSampleItems.Size = new System.Drawing.Size(614, 220);
            this.grp_AutoGenerateSampleItems.TabIndex = 3;
            this.grp_AutoGenerateSampleItems.TabStop = false;
            this.grp_AutoGenerateSampleItems.Text = "Auto generator of demo sample items";
            // 
            // lbl_NumberOfTitemsToBeInserted
            // 
            this.lbl_NumberOfTitemsToBeInserted.AutoSize = true;
            this.lbl_NumberOfTitemsToBeInserted.Location = new System.Drawing.Point(293, 187);
            this.lbl_NumberOfTitemsToBeInserted.Name = "lbl_NumberOfTitemsToBeInserted";
            this.lbl_NumberOfTitemsToBeInserted.Size = new System.Drawing.Size(166, 13);
            this.lbl_NumberOfTitemsToBeInserted.TabIndex = 13;
            this.lbl_NumberOfTitemsToBeInserted.Text = "lbl_NumberOfTitemsToBeInserted";
            // 
            // lbl_NumberOfItemsPerGroup
            // 
            this.lbl_NumberOfItemsPerGroup.Location = new System.Drawing.Point(0, 182);
            this.lbl_NumberOfItemsPerGroup.Name = "lbl_NumberOfItemsPerGroup";
            this.lbl_NumberOfItemsPerGroup.Size = new System.Drawing.Size(178, 20);
            this.lbl_NumberOfItemsPerGroup.TabIndex = 12;
            this.lbl_NumberOfItemsPerGroup.Text = "Number of Items per Group";
            this.lbl_NumberOfItemsPerGroup.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nmUpDn_NumberOfItemsPerGroup
            // 
            this.nmUpDn_NumberOfItemsPerGroup.Location = new System.Drawing.Point(184, 184);
            this.nmUpDn_NumberOfItemsPerGroup.Minimum = new decimal(new int[] {
            1,
            0,
            0,
            0});
            this.nmUpDn_NumberOfItemsPerGroup.Name = "nmUpDn_NumberOfItemsPerGroup";
            this.nmUpDn_NumberOfItemsPerGroup.Size = new System.Drawing.Size(78, 20);
            this.nmUpDn_NumberOfItemsPerGroup.TabIndex = 11;
            this.nmUpDn_NumberOfItemsPerGroup.Value = new decimal(new int[] {
            3,
            0,
            0,
            0});
            // 
            // lbl_Number_Of_Groups_in_Level3
            // 
            this.lbl_Number_Of_Groups_in_Level3.Enabled = false;
            this.lbl_Number_Of_Groups_in_Level3.Location = new System.Drawing.Point(0, 145);
            this.lbl_Number_Of_Groups_in_Level3.Name = "lbl_Number_Of_Groups_in_Level3";
            this.lbl_Number_Of_Groups_in_Level3.Size = new System.Drawing.Size(178, 17);
            this.lbl_Number_Of_Groups_in_Level3.TabIndex = 10;
            this.lbl_Number_Of_Groups_in_Level3.Text = "Number of groups in Level 3";
            this.lbl_Number_Of_Groups_in_Level3.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nm_UpDn_NumberOfGroupsInLevel3
            // 
            this.nm_UpDn_NumberOfGroupsInLevel3.Enabled = false;
            this.nm_UpDn_NumberOfGroupsInLevel3.Location = new System.Drawing.Point(184, 146);
            this.nm_UpDn_NumberOfGroupsInLevel3.Name = "nm_UpDn_NumberOfGroupsInLevel3";
            this.nm_UpDn_NumberOfGroupsInLevel3.Size = new System.Drawing.Size(78, 20);
            this.nm_UpDn_NumberOfGroupsInLevel3.TabIndex = 9;
            // 
            // lbl_Number_Of_Groups_in_Level2
            // 
            this.lbl_Number_Of_Groups_in_Level2.Enabled = false;
            this.lbl_Number_Of_Groups_in_Level2.Location = new System.Drawing.Point(0, 118);
            this.lbl_Number_Of_Groups_in_Level2.Name = "lbl_Number_Of_Groups_in_Level2";
            this.lbl_Number_Of_Groups_in_Level2.Size = new System.Drawing.Size(178, 17);
            this.lbl_Number_Of_Groups_in_Level2.TabIndex = 8;
            this.lbl_Number_Of_Groups_in_Level2.Text = "Number of groups in Level 2";
            this.lbl_Number_Of_Groups_in_Level2.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nm_UpDn_NumberOfGroupsInLevel2
            // 
            this.nm_UpDn_NumberOfGroupsInLevel2.Enabled = false;
            this.nm_UpDn_NumberOfGroupsInLevel2.Location = new System.Drawing.Point(184, 119);
            this.nm_UpDn_NumberOfGroupsInLevel2.Name = "nm_UpDn_NumberOfGroupsInLevel2";
            this.nm_UpDn_NumberOfGroupsInLevel2.Size = new System.Drawing.Size(78, 20);
            this.nm_UpDn_NumberOfGroupsInLevel2.TabIndex = 7;
            // 
            // lbl_Number_Of_Groups_in_Level1
            // 
            this.lbl_Number_Of_Groups_in_Level1.Location = new System.Drawing.Point(0, 92);
            this.lbl_Number_Of_Groups_in_Level1.Name = "lbl_Number_Of_Groups_in_Level1";
            this.lbl_Number_Of_Groups_in_Level1.Size = new System.Drawing.Size(178, 21);
            this.lbl_Number_Of_Groups_in_Level1.TabIndex = 6;
            this.lbl_Number_Of_Groups_in_Level1.Text = "Number of groups in Level 1";
            this.lbl_Number_Of_Groups_in_Level1.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // nm_UpDn_NumberOfGroupsInLevel1
            // 
            this.nm_UpDn_NumberOfGroupsInLevel1.Location = new System.Drawing.Point(184, 93);
            this.nm_UpDn_NumberOfGroupsInLevel1.Name = "nm_UpDn_NumberOfGroupsInLevel1";
            this.nm_UpDn_NumberOfGroupsInLevel1.Size = new System.Drawing.Size(78, 20);
            this.nm_UpDn_NumberOfGroupsInLevel1.TabIndex = 5;
            // 
            // txt_ItemAbbreviationPrefix
            // 
            this.txt_ItemAbbreviationPrefix.Location = new System.Drawing.Point(197, 58);
            this.txt_ItemAbbreviationPrefix.Name = "txt_ItemAbbreviationPrefix";
            this.txt_ItemAbbreviationPrefix.Size = new System.Drawing.Size(242, 20);
            this.txt_ItemAbbreviationPrefix.TabIndex = 3;
            // 
            // lbl_ItemAbbreviationPrefix
            // 
            this.lbl_ItemAbbreviationPrefix.Location = new System.Drawing.Point(8, 57);
            this.lbl_ItemAbbreviationPrefix.Name = "lbl_ItemAbbreviationPrefix";
            this.lbl_ItemAbbreviationPrefix.Size = new System.Drawing.Size(183, 20);
            this.lbl_ItemAbbreviationPrefix.TabIndex = 2;
            this.lbl_ItemAbbreviationPrefix.Text = "Item Abbreviation Prefix:";
            this.lbl_ItemAbbreviationPrefix.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // txt_Item_Name_Prefix
            // 
            this.txt_Item_Name_Prefix.Location = new System.Drawing.Point(197, 23);
            this.txt_Item_Name_Prefix.Name = "txt_Item_Name_Prefix";
            this.txt_Item_Name_Prefix.Size = new System.Drawing.Size(242, 20);
            this.txt_Item_Name_Prefix.TabIndex = 1;
            // 
            // lbl_ItemPrefix
            // 
            this.lbl_ItemPrefix.Location = new System.Drawing.Point(8, 22);
            this.lbl_ItemPrefix.Name = "lbl_ItemPrefix";
            this.lbl_ItemPrefix.Size = new System.Drawing.Size(183, 20);
            this.lbl_ItemPrefix.TabIndex = 0;
            this.lbl_ItemPrefix.Text = "Item Name Prefix:";
            this.lbl_ItemPrefix.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            // 
            // usrc_NavigationButtons1
            // 
            this.usrc_NavigationButtons1.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.usrc_NavigationButtons1.BackColor = System.Drawing.SystemColors.Control;
            this.usrc_NavigationButtons1.btn1_ToolTip_Text = "";
            this.usrc_NavigationButtons1.btn2_ToolTip_Text = "";
            this.usrc_NavigationButtons1.btn3_ToolTip_Text = "";
            this.usrc_NavigationButtons1.Button_NEXT_Enabled = true;
            this.usrc_NavigationButtons1.Buttons = NavigationButtons.Navigation.eButtons.OkCancel;
            this.usrc_NavigationButtons1.ExitQuestion = "Exit Program?";
            this.usrc_NavigationButtons1.Image_Cancel = null;
            this.usrc_NavigationButtons1.Image_EXIT = null;
            this.usrc_NavigationButtons1.Image_NEXT = ((System.Drawing.Image)(resources.GetObject("usrc_NavigationButtons1.Image_NEXT")));
            this.usrc_NavigationButtons1.Image_OK = ((System.Drawing.Image)(resources.GetObject("usrc_NavigationButtons1.Image_OK")));
            this.usrc_NavigationButtons1.Image_PREV = ((System.Drawing.Image)(resources.GetObject("usrc_NavigationButtons1.Image_PREV")));
            this.usrc_NavigationButtons1.Location = new System.Drawing.Point(1, 262);
            this.usrc_NavigationButtons1.Name = "usrc_NavigationButtons1";
            this.usrc_NavigationButtons1.Size = new System.Drawing.Size(625, 63);
            this.usrc_NavigationButtons1.TabIndex = 0;
            this.usrc_NavigationButtons1.Text_Cancel = "Exit";
            this.usrc_NavigationButtons1.Text_EXIT = "Exit";
            this.usrc_NavigationButtons1.Text_NEXT = "";
            this.usrc_NavigationButtons1.Text_OK = "";
            this.usrc_NavigationButtons1.Text_PREV = "";
            this.usrc_NavigationButtons1.Visible_EXIT = true;
            this.usrc_NavigationButtons1.Visible_NEXT = true;
            this.usrc_NavigationButtons1.Visible_PREV = true;
            this.usrc_NavigationButtons1.ButtonPressed += new NavigationButtons.usrc_NavigationButtons.delegate_button_pressed(this.usrc_NavigationButtons1_ButtonPressed);
            // 
            // Form_Items_Samples
            // 
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Inherit;
            this.ClientSize = new System.Drawing.Size(628, 326);
            this.Controls.Add(this.grp_AutoGenerateSampleItems);
            this.Controls.Add(this.rdb_InsertItemsManualy);
            this.Controls.Add(this.rdb_AutoGenerateDemoItems);
            this.Controls.Add(this.usrc_NavigationButtons1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.Name = "Form_Items_Samples";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form_ShopB_Items_Samples";
            this.grp_AutoGenerateSampleItems.ResumeLayout(false);
            this.grp_AutoGenerateSampleItems.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.nmUpDn_NumberOfItemsPerGroup)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel3)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.nm_UpDn_NumberOfGroupsInLevel1)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private NavigationButtons.usrc_NavigationButtons usrc_NavigationButtons1;
        private System.Windows.Forms.RadioButton rdb_InsertItemsManualy;
        private System.Windows.Forms.RadioButton rdb_AutoGenerateDemoItems;
        private System.Windows.Forms.GroupBox grp_AutoGenerateSampleItems;
        private System.Windows.Forms.TextBox txt_Item_Name_Prefix;
        private System.Windows.Forms.Label lbl_ItemPrefix;
        private System.Windows.Forms.Label lbl_NumberOfItemsPerGroup;
        private System.Windows.Forms.NumericUpDown nmUpDn_NumberOfItemsPerGroup;
        private System.Windows.Forms.Label lbl_Number_Of_Groups_in_Level3;
        private System.Windows.Forms.NumericUpDown nm_UpDn_NumberOfGroupsInLevel3;
        private System.Windows.Forms.Label lbl_Number_Of_Groups_in_Level2;
        private System.Windows.Forms.NumericUpDown nm_UpDn_NumberOfGroupsInLevel2;
        private System.Windows.Forms.Label lbl_Number_Of_Groups_in_Level1;
        private System.Windows.Forms.NumericUpDown nm_UpDn_NumberOfGroupsInLevel1;
        private System.Windows.Forms.TextBox txt_ItemAbbreviationPrefix;
        private System.Windows.Forms.Label lbl_ItemAbbreviationPrefix;
        private System.Windows.Forms.Label lbl_NumberOfTitemsToBeInserted;
    }
}