#region LICENSE 
/*
 This Source Code Form is subject to the terms of the Tangenta Public License, v. 1.0. 
 If a copy of the Tangenta Public License (TPL) was not distributed with this 
 file, You can obtain one at  https://github.com/dstrucl/Tangenta40/wiki/LICENCE 
*/
#endregion
using System;
using System.Collections.Generic;

using System.Data;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using System.Reflection;
using LanguageControl;

namespace TangentaSampleDB
{
    public static class lng
    {
 public static ltext s_Form_EditMyOrgSampleData = new ltext( new string[]{"Sample data for organisation name Company1. You can change them to your organisation data.", "Vzorčni podatki organizacije z imenom Podjetje1, ki jih lahko spremenite v tem dialogu v podatke vaše organizacije."});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_EditMyOrgSampleData.cs

 public static ltext s_YouHaveChangedSomeDataButNotAllSampleData_YouShouldChangeAllSampleDataToYourRealData = new ltext( new string[]{"You have only changed some of sample data!\r\nIf you want to run this application with your real data, press OK and then change all sample data to your real organisation data.If you want to run this application with your modified sample data press Cancel", "Spremenili ste samo nekatere vzorčne podatke.\r\nČe želite, da bo program uporabljal prave podatke pritisnite gumb \"V redu\" in spremenite vse vzorčne podatke v prave podatke.\r\nČe želite, da bo program uporabljal spremenjene vzorčne podatke in tekel kot demo aplikacija pritisnite gumb \"Prekini\""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_EditMyOrgSampleData.cs

 public static ltext s_IfYouAreRunningThisApplicationOnlyForDemoOrTestPurposesPressYes = new ltext( new string[]{"If you are running this application only for demo or test pruposes select Yes, otherwise press No ?", 
                                                                                                            "V kolikor sta zagnali to aplikacijo zgolj z namenom preizkusa ali testiranja izberite Da sicer izberite Ne ?"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_NumberOfItemsToInsert = new ltext( new string[]{"Number of items to insert ", "Število artiklov za vpis "});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_Number_Of_Items_per_group = new ltext( new string[]{"Number of items in group", "Število artiklov ali storitev v skupini"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_Number_Of_Groups_in_Level1 = new ltext( new string[]{"Number of groups in Level 1", "Število skupin artiklov ali storitev nivoja 1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_Number_Of_Groups_in_Level2 = new ltext( new string[]{"Number of groups in Level 2", "Število skupin artiklov ali storitev nivoja 2"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_Number_Of_Groups_in_Level3 = new ltext( new string[]{"Number of groups in Level 3", "Število skupin artiklov ali storitev nivoja 3"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_ItemAbbreviationPrefix = new ltext( new string[]{"Item name abbreviation prefix", "Predpona za skrajšano ime artikla ali storitve"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_lbl_ItemNamePrefix = new ltext( new string[]{"Item name prefix", "Predpona za ime artikla ali storitve"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_GeneratorOfSampleItems = new ltext( new string[]{"Generator of sample items", "Generator vzorčnih (demo) artiklov oziroma storitev"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_rdb_AutoGenerateDemoItems = new ltext( new string[]{"Auto generate demo items", "Atomatsko generiraj vzorčne artikle oziroma storitve"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_rdb_InsertItemsManualy = new ltext( new string[]{"Insert Manually", "Ročni vnos artiklov/storitev"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_InsertSampleItems_for_shop = new ltext( new string[]{"Select items insertion for shop", "Izberite vnos artiklov/storitev za prodajalno "});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext ShopB_Item_Name_Item = new ltext( new string[]{"BItem","BArtikel"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext ShopB_Item_Abbreviation_SB = new ltext( new string[]{"BItm", "BArt"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext ShopC_Item_Name_Item = new ltext( new string[]{"CItem", "CArtikel"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext ShopC_Item_Abbreviation_SB = new ltext( new string[]{"CItm", "CArt"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_Shop_B = new ltext( new string[]{"B", "B"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_Question = new ltext( new string[]{"?", "?"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\Form_Items_Samples.cs

 public static ltext s_JobInPercentDone = new ltext( new string[]{"Job done:", "Količina opravljenaga dela v odstotkih:"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_WriteItemsToDatabase = new ltext( new string[]{"Number of items to write:", "Število artiklov za vpis:"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_ItemsWrittenToDB = new ltext( new string[]{"Number of items inserted to database:", "Število artiklov vpisanih v podatkovno bazo:"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Piece = new ltext( new string[]{"Piece", "Komad"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_PieceAbr = new ltext( new string[]{"Pcs", "Kom."});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_SelectCountryWhereYouPayTaxes = new ltext( new string[]{"Country of tax residency", "Država katere ste davčni zavezanec"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Name = new ltext( new string[]{"Organisation name", "Ime organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Name_v = new ltext( new string[]{"Organisation1", "Podjetje1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Name = new ltext( new string[]{"Enter your organisation name", "Vpišite ime vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Tax_ID = new ltext( new string[]{"Organisation VAT number", "Davčna številka"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Tax_ID_v = new ltext( new string[]{"12345678", "12345678"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Tax_ID = new ltext( new string[]{"Enter your organisation VAT number", "Vpišite davčno številko"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Registration_ID = new ltext( new string[]{"Your Organisation Registration Number", "Matična številka vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Registration_ID_v = new ltext( new string[]{"00000001", "00000001"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Registration_ID = new ltext( new string[]{"Enter Your Organisation Registration Number", "Vpišite matično številko vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_TaxPayer = new ltext( new string[]{"Tax Payer", "Davčni zavezanec"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_TaxPayer_v = new ltext( new string[]{"00000001", "00000001"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_TaxPayer = new ltext( new string[]{"Check if your organisation is tax-payer", "Odkljukajte če je vaša organizacija davčni zavezanec"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Comment1 = new ltext( new string[]{"Comment 1", "Komentar 1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Comment1_v = new ltext( new string[]{"VAT payer", "Davčni zavezanec za DDV"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Comment1 = new ltext( new string[]{"Write comment 1 about your organisation", "Vpišite komentar 1 o vaši organizaciji (primer:Davčni zavezanec za DDV)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_OrganisationTYPE = new ltext( new string[]{"Type of organisation", "Tip organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_OrganisationTYPE_v = new ltext( new string[]{"ltd", "d.o.o."});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_OrganisationTYPE = new ltext( new string[]{"Enter type of your organisation (ltd., gov.,)", "Vpišite vrsto vaše organizacije (d.d.,d.o.o.,javni zavod,..)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_PhoneNumber = new ltext( new string[]{"Organisation phone number", "Številka telefona vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_PhoneNumber_v = new ltext( new string[]{"000000", "0000000"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_PhoneNumber = new ltext( new string[]{"Enter your organisation phone number", "Vpišite številko telefona vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_FaxNumber = new ltext( new string[]{"Organisation fax number", "Številka fax-a vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_FaxNumber_v = new ltext( new string[]{"000000", "00000"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_FaxNumber = new ltext( new string[]{"Enter your organisation fax number", "Vpišite številko fax-a vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Email = new ltext( new string[]{"Organisation email", "Elektronski naslov vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Email_v = new ltext( new string[]{"Organisation1@email.com", "Podjetje1@email.com"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Email = new ltext( new string[]{"Enter your organisation email", "Vpišite elektronski naslov (email) vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_HomePage = new ltext( new string[]{"Organisation homepage", "Domači naslov vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_HomePage_v = new ltext( new string[]{"www.Organisation1.com", "www.Podjetje1.si"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_HomePage = new ltext( new string[]{"Enter your organisation homepage", "Vpišite domači naslov (homepage) vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Bank_Name = new ltext( new string[]{"The name of bank of your organisation bank account", "Ime banke vašega TRR računa vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Bank_Name_v = new ltext( new string[]{"Bank1", "Banka1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Bank_Name = new ltext( new string[]{"Enter the name of bank of your organisation bank account", "Vpišite ime banke vašega TRR računa vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Bank_Tax_ID = new ltext( new string[]{"Bank VAT number", "Davčna številka banke"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Bank_Tax_ID_v = new ltext( new string[]{"23456789", "23456789"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Bank_Tax_ID = new ltext( new string[]{"Enter your bank VAT number", "Vpišite davčno številko vaše banke"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Bank_Registration_ID = new ltext( new string[]{"Your bank Registration Number", "Matična številka vaše banke"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Bank_Registration_ID_v = new ltext( new string[]{"00000003", "00000003"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Bank_Registration_ID = new ltext( new string[]{"Enter Your Organisation Registration Number", "Vpišite matično številko vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_TRR = new ltext( new string[]{"Bank account", "Številka TRR računa vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_TRR_v = new ltext( new string[]{"0000-0000-000-000", "0000-0000-000-000"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_TRR = new ltext( new string[]{"Enter bank account", "Vpišite številko TRR računa vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_TRR_Description = new ltext( new string[]{"Bank account desc.", "Opis TRR računa"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_TRR_Description_v = new ltext( new string[]{"Casshier bank Account", "Račun za prihodke od blagajne"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_TRR_Description = new ltext( new string[]{"Enter bank Casshier account description", "Vpišite opis namena TRR računa vaše organizacije"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_TRR_Active = new ltext( new string[]{"Bank account Active", "TRR račun je aktiven"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_TRR_Active_v = new ltext( new string[]{"Check if bank account is Active", "Označite s kljukico, da je bančni račun aktiven"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Logo = new ltext( new string[]{"Logo", "Logotip"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Logo_v = new ltext( new string[]{"Select Logo Image", "Izberite Logotip"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_StreetName = new ltext( new string[]{"Street", "Cesta"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_StreetName_v = new ltext( new string[]{"MyStreet1", "Cesta1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Address_StreetName = new ltext( new string[]{"Enter street name", "Vpišite ime ceste"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_HouseNumber = new ltext( new string[]{"House number", "Hišna številka"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_HouseNumber_v = new ltext( new string[]{"1", "1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Address_HouseNumber = new ltext( new string[]{"Enter house number", "Vpišite hišno številko"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_ZIP = new ltext( new string[]{"ZIP", "Številka pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_ZIP_v = new ltext( new string[]{"Zip1", "ŠP1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Address_ZIP = new ltext( new string[]{"Enter ZIP", "Vpišite številko pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_City = new ltext( new string[]{"City", "Mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_City_v = new ltext( new string[]{"City1", "Mesto1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Address_City = new ltext( new string[]{"Enter city", "Vpišite mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_State = new ltext( new string[]{"State", "Dežela"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_State_v = new ltext( new string[]{"", ""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Address_State = new ltext( new string[]{"Enter State", "Vpišite deželo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_Country = new ltext( new string[]{"Country", "Država"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_Country_v = new ltext( new string[]{"Enter country", "Vpišite državo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_Country_ISO_3166_a2 = new ltext( new string[]{"Country abbreviation (2 characters)", "Okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_Country_ISO_3166_a2_v = new ltext( new string[]{"Enter country abbreviation (2 characters)", "Vpišite okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_Country_ISO_3166_a3 = new ltext( new string[]{"Country abbreviation (3 characters)", "Okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_Country_ISO_3166_a3_v = new ltext( new string[]{"Enter country abbreviation (3 characters)", "Vpišite okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Address_Country_ISO_3166_num = new ltext( new string[]{"Country code number", "Kodna številka države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Address_Country_ISO_3166_num_v = new ltext( new string[]{"Enter country iso code number", "Vpišite kodno ISO 3166 številko države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_StreetName = new ltext( new string[]{"Street", "Cesta"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_StreetName_v = new ltext( new string[]{"MyStreet1", "Cesta1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Address_StreetName = new ltext( new string[]{"Enter street name", "Vpišite ime ceste"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_HouseNumber = new ltext( new string[]{"House number", "Hišna številka"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_HouseNumber_v = new ltext( new string[]{"1", "1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Address_HouseNumber = new ltext( new string[]{"Enter house number", "Vpišite hišno številko"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_ZIP = new ltext( new string[]{"ZIP", "Številka pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_ZIP_v = new ltext( new string[]{"Zip1", "ŠtevilkaPošte1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Address_ZIP = new ltext( new string[]{"Enter ZIP", "Vpišite številko pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_City = new ltext( new string[]{"City", "Mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_City_v = new ltext( new string[]{"City1", "Mesto1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Address_City = new ltext( new string[]{"Enter city", "Vpišite mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_State = new ltext( new string[]{"State", "Dežela"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_State_v = new ltext( new string[]{"", ""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Address_State = new ltext( new string[]{"Enter State", "Vpišite deželo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_Country_v = new ltext( new string[]{"Enter country", "Vpišite državo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_Country_ISO_3166_a2 = new ltext( new string[]{"Country abbreviation (2 characters)", "Okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_Country_ISO_3166_a2_v = new ltext( new string[]{"Enter country abbreviation (2 characters)", "Vpišite okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_Country_ISO_3166_a3 = new ltext( new string[]{"Country abbreviation (3 characters)", "Okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_Country_ISO_3166_a3_v = new ltext( new string[]{"Enter country abbreviation (3 characters)", "Vpišite okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Address_Country_ISO_3166_num = new ltext( new string[]{"Country code number", "Kodna številka države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Address_Country_ISO_3166_num_v = new ltext( new string[]{"Enter country iso code number", "Vpišite kodno ISO 3166 številko države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_OfficeName = new ltext( new string[]{"Office name", "Ime poslovne enote"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_OfficeName_v = new ltext( new string[]{"Office1", "Pisarna1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_OfficeName = new ltext( new string[]{"Enter office name", "Vpišite ime poslovne enote"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_OfficeShortName = new ltext( new string[]{"Office short name", "Skrajšano ime poslovne enote"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_OfficeShortName_v = new ltext( new string[]{"Off1", "Pis1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_OfficeShortName = new ltext( new string[]{"Enter office short name", "Vpišite skrajšano ime poslovne enote"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_FirstName = new ltext( new string[]{"Organisation administrator First Name", "Ime glavnega administratorja v podjetju"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_FirstName_v = new ltext( new string[]{"Organisation1Person1FirstName", "ImeOsebe1Podjetja1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_FirstName = new ltext( new string[]{"Enter organisation administrator First Name", "Vpišite ime glavnega administratorja, ki bo imel vse uporabniške pravice"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_LastName = new ltext( new string[]{"Organisation administrator Last Name", "Priimek glavnega administratorja v podjetju"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_LastName_v = new ltext( new string[]{"Organisation1Person1LastName", "PrimekOsebe1Podjetja1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_LastName = new ltext( new string[]{"Enter organisation administrator Lasst Name who gets all user rights", "Vpišite priimek glavnega administratorja, ki bo imel vse uporabniške pravice"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Gender = new ltext( new string[]{"Administrator gender", "Spol glavnega administratorja v podjetju"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Gender_v = new ltext( new string[]{"Enter gender of administrator", "Označite spol administratorja, ki bo imel vse uporabniške pravice"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_DateOfBirth = new ltext( new string[]{"Administrator date of birth", "Datum rojstva glavnega administratorja v podjetju"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_DateOfBirth_v = new ltext( new string[]{"Enter date of birth of administrator", "Vpišite datum rojstva glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_UserName = new ltext( new string[]{"Administrator user name", "Uporabniško ime glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_UserName_v = new ltext( new string[]{"Organisation1Person1UserName1", "UporabniškoIme1Osebe1Podjetja1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_UserName = new ltext( new string[]{"Enter administrator user name", "Vpišiti uporabniško ime glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Password = new ltext( new string[]{"Administrator password", "Skrbniško geslo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Password_v = new ltext( new string[]{"12345", "12345"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Password = new ltext( new string[]{"Enter administrator password", "Vpišite geslo glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Job = new ltext( new string[]{"Administrator Job Title", "Delovno mesto glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Job_v = new ltext( new string[]{"Organisation1Person1Job", "DelovnoMestoOsebe1Podjetja1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Job = new ltext( new string[]{"Organisation1Person1Job", "DelovnoMestoOsebe1Podjetja1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Description = new ltext( new string[]{"Administrator description", "Glavni administrator opis"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Description_v = new ltext( new string[]{"Organisation1Person1Description", "Osebe1Podjetja1Opis"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Description = new ltext( new string[]{"Enter job description of administrator", "Vpišite opis dela glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Tax_ID = new ltext( new string[]{"Administrator's Tax ID", "Davčna številka glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Tax_ID_v = new ltext( new string[]{"12345678", "12345678"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Tax_ID = new ltext( new string[]{"Enter administrator's Tax ID", "Vpišite davčno številka glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Registration_ID = new ltext( new string[]{"Administrator's registration ID", "EMŠO glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Registration_ID_v = new ltext( new string[]{"", ""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Registration_ID = new ltext( new string[]{"Enter administrator's registration ID", "Vpišite EMŠO glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_GsmNumber = new ltext( new string[]{"Administrator's mobile phone naumber", "Mobilni telefon glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_GsmNumber_v = new ltext( new string[]{"", ""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_GsmNumber = new ltext( new string[]{"Administrator's mobile phone naumber", "Vpišite številko mobilnega telefona glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_PhoneNumber = new ltext( new string[]{"Administrator's phone naumber", "Telefon glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_PhoneNumber_v = new ltext( new string[]{"00386 15839410", "0038615839410"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_PhoneNumber = new ltext( new string[]{"Enter administrator's phone naumber", "Vpišite telefon glavnega administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Person_Email = new ltext( new string[]{"Administrator's email", "Email administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Person_Email_v = new ltext( new string[]{"Person1@mail.com", "Person1@mail.com"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Person_Email = new ltext( new string[]{"Enter Administrator's email", "Vpišite email administratorja"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_StreetName = new ltext( new string[]{"Street", "Cesta"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_StreetName_v = new ltext( new string[]{"MyStreet1", "Cesta1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Person_Address_StreetName = new ltext( new string[]{"Enter street name", "Vpišite ime ceste"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_HouseNumber = new ltext( new string[]{"House number", "Hišna številka"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_HouseNumber_v = new ltext( new string[]{"1", "1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Person_Address_HouseNumber = new ltext( new string[]{"Enter house number", "Vpišite hišno številko"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_ZIP = new ltext( new string[]{"ZIP", "Številka pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_ZIP_v = new ltext( new string[]{"Zip1", "ŠtevilkaPošte1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Person_Address_ZIP = new ltext( new string[]{"Enter ZIP", "Vpišite številko pošte"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_City = new ltext( new string[]{"City", "Mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_City_v = new ltext( new string[]{"City1", "Mesto1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Person_Address_City = new ltext( new string[]{"Enter city", "Vpišite mesto"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_State = new ltext( new string[]{"State", "Dežela"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_State_v = new ltext( new string[]{"", ""});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sh_MyOrg_Office_Person_Address_State = new ltext( new string[]{"Enter State", "Vpišite deželo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_Country_v = new ltext( new string[]{"Enter country", "Vpišite državo"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_Country_ISO_3166_a2 = new ltext( new string[]{"Country abbreviation (2 characters)", "Okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_Country_ISO_3166_a2_v = new ltext( new string[]{"Enter country abbreviation (2 characters)", "Vpišite okrajšavo za državo (2 znaka)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_Country_ISO_3166_a3 = new ltext( new string[]{"Country abbreviation (3 characters)", "Okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_Country_ISO_3166_a3_v = new ltext( new string[]{"Enter country abbreviation (3 characters)", "Vpišite okrajšavo za državo (3 znaki)"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext sl_MyOrg_Office_Person_Address_Country_ISO_3166_num = new ltext( new string[]{"Country code number", "Kodna številka države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrg_Office_Person_Address_Country_ISO_3166_num_v = new ltext( new string[]{"Enter country iso code number", "Vpišite kodno ISO 3166 številko države"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext PriceList_Description = new ltext( new string[]{"Price list for usual customers.", "Cenik za stalne stranke."});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Comment1 = new ltext( new string[]{"Comment 1", "Komentar 1"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_BankAccount = new ltext( new string[]{"Bank Account", "Bančni račun"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Shop_C = new ltext( new string[]{"C", "C"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_MyOrganisation = new ltext( new string[]{"My organisation",
                                                    "Moja oragnizacija"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Office = new ltext( new string[]{"Office",
                                                    "Poslovna enota"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Description = new ltext( new string[]{"Description", "opis"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Person = new ltext( new string[]{"Person",
                                          "Oseba"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Address = new ltext( new string[]{"Address",
                                           "Naslov"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Country = new ltext( new string[]{"Country",
                                         "Država"});   // referenced in C:\Tangenta40\TANGENTA\TangentaSampleDB\SampleDB.cs

 public static ltext s_Bank = new ltext(new string[] { "Bank", "Banka" });
    }
}
