//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiscalVerificationOfInvoices_SLO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int MessageBox_Length {
            get {
                return ((int)(this["MessageBox_Length"]));
            }
            set {
                this["MessageBox_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<schema xmlns=\"http://www.w3.org/2001/XMLS" +
            "chema\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ds=\"http://www.w3.org/2" +
            "000/09/xmldsig#\" xmlns:fu=\"http://www.fu.gov.si/\" targetNamespace=\"http://www.fu" +
            ".gov.si/\" elementFormDefault=\"qualified\">\n\t<import namespace=\"http://www.w3.org/" +
            "2000/09/xmldsig#\" schemaLocation=\"http://www.w3.org/TR/2002/REC-xmldsig-core-200" +
            "20212/xmldsig-core-schema.xsd\"/>\n\t<element name=\"InvoiceListRequest\">\n\t\t<annotat" +
            "ion>\n\t\t\t<documentation>Vsebina in oblika sporočila s podatki o računu. / Conte" +
            "nt and form of the message with data about the invoice.</documentation>\n\t\t</anno" +
            "tation>\n\t\t<complexType>\n\t\t\t<sequence>\n\t\t\t\t<element name=\"Header\" type=\"fu:Header" +
            "Type\">\n\t\t\t\t\t<annotation>\n\t\t\t\t\t\t<documentation>Glava sporočila / Message header<" +
            "/documentation>\n\t\t\t\t\t</annotation>\n\t\t\t\t</element>\n\t\t\t\t<element name=\"InvoiceList" +
            "\">\n\t\t\t\t\t<annotation>\n\t\t\t\t\t\t<documentation>Seznam računov</documentation>\n\t\t\t\t\t</" +
            "annotation>\n\t\t\t\t\t<complexType>\n\t\t\t\t\t\t<sequence minOccurs=\"2\" maxOccurs=\"500\">\n\t\t" +
            "\t\t\t\t\t<element name=\"RecordInfo\">\n\t\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t\t<documentation>Po" +
            "samezni zapis</documentation>\n\t\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t\t\t<complexType>\n\t\t\t\t\t\t" +
            "\t\t\t<sequence>\n\t\t\t\t\t\t\t\t\t\t<element name=\"RecordNumber\" type=\"integer\">\n\t\t\t\t\t\t\t\t\t\t\t" +
            "<annotation>\n\t\t\t\t\t\t\t\t\t\t\t\t<documentation>Zaporedna številka zapisa</documentation" +
            ">\n\t\t\t\t\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t\t\t\t\t<element name=\"Invoice" +
            "\" type=\"fu:InvoiceType\">\n\t\t\t\t\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t\t\t\t\t<documentation>Vpiš" +
            "ejo se podatki o računu, ki je izdan z uporabo elektronske naprave. / Data are e" +
            "ntered about the invoice, which is issued with usage of the electronic device.</" +
            "documentation>\n\t\t\t\t\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t\t\t\t</sequence" +
            ">\n\t\t\t\t\t\t\t\t</complexType>\n\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t</sequence>\n\t\t\t\t\t</complexType>" +
            "\n\t\t\t\t</element>\n\t\t\t\t<element ref=\"ds:Signature\"/>\n\t\t\t</sequence>\n\t\t\t<attribute n" +
            "ame=\"Id\" type=\"string\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Atribut za potrebe " +
            "digitalnega podpisa. V njem imamo id, ki se veže na digitalni podpis. / Attribut" +
            "e for needs of the digital signature. In it we have id, which is linked to the d" +
            "igital signature.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</attribute>\n\t\t</complexT" +
            "ype>\n\t</element>\n\t<element name=\"InvoiceListResponse\">\n\t\t<annotation>\n\t\t\t<docume" +
            "ntation>Odgovor za oddajo računa. / Response for submitting the invoice.</docum" +
            "entation>\n\t\t</annotation>\n\t\t<complexType>\n\t\t\t<sequence>\n\t\t\t\t<element name=\"Heade" +
            "r\" type=\"fu:HeaderResponseType\"/>\n\t\t\t\t<element name=\"InvoiceListReply\" minOccurs" +
            "=\"0\">\n\t\t\t\t\t<complexType>\n\t\t\t\t\t\t<sequence minOccurs=\"2\" maxOccurs=\"500\">\n\t\t\t\t\t\t\t<" +
            "element name=\"RecordReply\">\n\t\t\t\t\t\t\t\t<complexType>\n\t\t\t\t\t\t\t\t\t<sequence>\n\t\t\t\t\t\t\t\t\t\t" +
            "<element name=\"RecordNumber\" type=\"integer\">\n\t\t\t\t\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t\t\t\t" +
            "\t<documentation>Zaporedna številka zapisa</documentation>\n\t\t\t\t\t\t\t\t\t\t\t</annotatio" +
            "n>\n\t\t\t\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t\t\t\t\t<element name=\"ProtectedID\">\n\t\t\t\t\t\t\t\t\t\t\t<annot" +
            "ation>\n\t\t\t\t\t\t\t\t\t\t\t\t<documentation>ZOI, ki je povezan s tem zapisom.</documentati" +
            "on>\n\t\t\t\t\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t\t\t\t\t\t<simpleType>\n\t\t\t\t\t\t\t\t\t\t\t\t<restriction ba" +
            "se=\"string\">\n\t\t\t\t\t\t\t\t\t\t\t\t\t<length value=\"32\"/>\n\t\t\t\t\t\t\t\t\t\t\t\t</restriction>\n\t\t\t\t\t\t" +
            "\t\t\t\t\t</simpleType>\n\t\t\t\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t\t\t\t\t<element name=\"UniqueInvoiceID" +
            "\" type=\"fu:UUIDType\">\n\t\t\t\t\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t\t\t\t\t<documentation>Enkratn" +
            "i identifikator sporočila. / Unique identifier of the message.</documentation>\n\t" +
            "\t\t\t\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t\t\t\t</sequence>\n\t\t\t\t\t\t\t\t</comp" +
            "lexType>\n\t\t\t\t\t\t\t</element>\n\t\t\t\t\t\t</sequence>\n\t\t\t\t\t</complexType>\n\t\t\t\t</element>\n" +
            "\t\t\t\t<element name=\"Error\" type=\"fu:ErrorType\" minOccurs=\"0\"/>\n\t\t\t\t<element ref=\"" +
            "ds:Signature\" minOccurs=\"0\"/>\n\t\t\t</sequence>\n\t\t\t<attribute name=\"Id\" type=\"strin" +
            "g\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Atribut za potrebe digitalnega podpisa." +
            " V njem imamo id, ki se veže na digitalni podpis./ Attribute for needs of the di" +
            "gital signature. In it we have id, which is linked to the digital signature.</do" +
            "cumentation>\n\t\t\t\t</annotation>\n\t\t\t</attribute>\n\t\t</complexType>\n\t</element>\n\t<co" +
            "mplexType name=\"InvoiceType\">\n\t\t<annotation>\n\t\t\t<documentation>Račun / Invoice</" +
            "documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name=\"TaxNumber\" type=\"f" +
            "u:TaxNumberType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentati" +
            "on>Vpiše se davčna številka zavezanca, ki je izdal račun. / The tax number of th" +
            "e person liable, who has issued the invoice, is entered.</documentation>\n\t\t\t\t</a" +
            "nnotation>\n\t\t\t</element>\n\t\t\t<element name=\"IssueDateTime\" type=\"fu:dateTime\" min" +
            "Occurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se datum in" +
            " čas izdaje računa, ki je naveden na računu. Podatek se vpiše v formatu LLLL-MM-" +
            "DDTUU:MM:SS. / Date and time of issuing the invoice, which is stated on the invo" +
            "ice, are entered. The data is entered in the following format YYYY-MM-DDTHH:MM:S" +
            "S.\n</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"NumberingS" +
            "tructure\" type=\"fu:NumberingStructureType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<ann" +
            "otation>\n\t\t\t\t\t<documentation>Vpiše se oznaka načina dodeljevanja številk računom" +
            ": C – centralno na nivoju poslovnega prostora, B – po posamezni elektronski napr" +
            "avi (blagajna) Oznaka pojasnjuje na kakšen način se računom dodeljujejo številke" +
            ". Številke računov se lahko dodeljujejo centralno na nivoju poslovnega prostora " +
            "ali posamično na elektronski napravi za izdajanje računov. / The mark is entered" +
            " for the method of assigning numbers to invoices: C - centrally at the level of " +
            "business premises, B - per individual electronic device (cash register). The mar" +
            "k explains the method for assigning numbers to invoices. Invoice numbers may be " +
            "assigned centrally at the level of business premises or individually on the elec" +
            "tronic device for issuing invoices.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</eleme" +
            "nt>\n\t\t\t<element name=\"InvoiceIdentifier\" type=\"fu:IdentifierType\" minOccurs=\"1\" " +
            "maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se številka izdanega r" +
            "ačuna. Vpiše se tudi številka dokumenta, ki spreminja prvotni račun (dobropis, s" +
            "torno,…) v primeru izvajanja postopka potrjevanja naknadne spremembe podatkov na" +
            " računu, ki spreminja prvoten račun in se nanj nedvoumno nanaša. Številka računa" +
            " je sestavljena iz treh delov: oznaka poslovnega prostora; oznaka elektronske na" +
            "prave za izdajanje računov; zaporedna številka računa. Številka računa se na rač" +
            "unu navede v naslednji obliki: oznaka poslovnega prostora-oznaka elektronske nap" +
            "rave-zaporedna številka računa. Primer: TRGOVINA1-BLAG2-1234 Podatki se vpisujej" +
            "o ločeno. / The number of the issued invoice is entered. The number of the docum" +
            "ent is also entered, which changes the original invoice (credit, reversing, etc." +
            ") in cases of performing the procedure for verification of subsequent changes of" +
            " data on the invoice, which changes the original invoice and refers to it with r" +
            "easonable certainty. The invoice number includes three parts: mark of business p" +
            "remises; mark of the electronic device for issuing invoices; sequence number of " +
            "the invoice. The invoice number is stated on the invoice in the following form: " +
            "mark of business premises-mark of the electronic device-sequence invoice number." +
            " Example: TRGOVINA1-BLAG2-1234. Data are entered separately.</documentation>\n\t\t\t" +
            "\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"CustomerVATNumber\" type=\"fu:Custo" +
            "merVATType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vp" +
            "iše se davčna številka oziroma identifikacijska številka za namene DDV kupca ozi" +
            "roma naročnika v primeru, ko so ti podatki v skladu z davčnimi predpisi navedeni" +
            " na računu. Podatek se vpiše, če je naveden na računu. / The tax number is enter" +
            "ed or identification number for VAT purposes of the buyer or ordering party in c" +
            "ases when these data are stated on the invoice in accordance with tax regulation" +
            "s.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"InvoiceAmou" +
            "nt\" type=\"fu:AmountType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<doc" +
            "umentation>Vnese se skupni znesek računa. Vpiše se znesek računa skupaj z DDV in" +
            " ostalimi davki/dajatvami, zmanjšan za zneske popustov. Decimalno ločilo je pika" +
            ". / The total amount of the invoice is entered. The amount of the invoice is ent" +
            "ered together with VAT and other taxes/duties, decreased for amounts of discount" +
            "s. The decimal separator is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</elemen" +
            "t>\n\t\t\t<element name=\"ReturnsAmount\" type=\"fu:AmountType\" minOccurs=\"0\" maxOccurs" +
            "=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se znesek povračil na računu, k" +
            "i se priznajo kupcu (npr. na podlagi dobropisa za vračilo embalaže). Podatek se " +
            "vpiše le, če na računu obstajajo povračila. Decimalno ločilo je pika. / The amou" +
            "nt of refunds on the invoice, which are recognized to the buyer (e.g. on the bas" +
            "is of credit for returning packaging), is entered. The data is entered only if t" +
            "here are refunds on the invoice. The decimal separator is a dot.</documentation>" +
            "\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"PaymentAmount\" type=\"fu:Amoun" +
            "tType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše s" +
            "e znesek računa za plačilo. Decimalno ločilo je pika. / The amount of the invoic" +
            "e for payment is entered. The decimal separator is a dot.</documentation>\n\t\t\t\t</" +
            "annotation>\n\t\t\t</element>\n\t\t\t<element name=\"TaxesPerSeller\" type=\"fu:TaxesPerSel" +
            "lerType\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se vrednos" +
            "t osnov po vrsti davka ali dajatve, razdeljeno po davčnih stopnjah, in pripadajo" +
            "či davek ali dajatev, vrednost dobav na podlagi posebnih ureditev, dobav pri kat" +
            "erih je plačnik DDV kupec blaga ali naročnik storitve, oproščenih dobav in neobd" +
            "avčljivih dobav, ločeno po davčnih številkah davčnih zavezancev. / The value is " +
            "entered for bases according to types of taxes or duties, separated per tax rates" +
            ", and associated taxes or duties, value of supplies on the basis of special arra" +
            "ngements, supplies where the payer of VAT is the buyer of goods or party orderin" +
            "g services, exempt supplies and non-taxable supplies, separated according to tax" +
            " numbers of taxpayers.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<eleme" +
            "nt name=\"OperatorTaxNumber\" type=\"fu:TaxNumberType\" minOccurs=\"0\" maxOccurs=\"1\">" +
            "\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše še davčna številka fizične osebe (op" +
            "eraterja), ki izda račun z uporabo elektronske naprave za izdajanje računov. V p" +
            "rimeru izdaje računa preko samopostrežnih elektronskih naprav oziroma ko se raču" +
            "n izda brez prisotnosti fizične osebe, se vpiše davčna številka zavezanca. Če os" +
            "eba nima slovenske davčne številke, se podatek ne vpisuje. / The tax number is e" +
            "ntered of the individual (operator), who issues the invoice with the usage of th" +
            "e electronic device for issuing invoices. In cases of issuing invoices via self-" +
            "service electronic devices or when invoices are issued without the presence of i" +
            "ndividuals, the tax number of the person liable is entered. The data is not ente" +
            "red if the person has no Slovene tax number.</documentation>\n\t\t\t\t</annotation>\n\t" +
            "\t\t</element>\n\t\t\t<element name=\"ForeignOperator\" type=\"boolean\" minOccurs=\"0\" max" +
            "Occurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se true, če fizična oseba" +
            " (operater), ki izda račun z uporabo elektronske naprave, nima slovenske davčne " +
            "številke, drugače false (1 - true, 0 – false). / You enter »true« if the individ" +
            "ual (operator), who issues the invoice with the usage of the electronic device, " +
            "has no Slovene tax number, otherwise »false« (1 – true, 0 – false).</documentati" +
            "on>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"ProtectedID\" minOccurs=\"1\"" +
            " maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se zaščitna oznaka iz" +
            "dajatelja računa. Zaščitna oznaka je sestavljena iz 32 znakov v heksadecimalnem " +
            "formatu. Primer: 8202f0f963e37a2258b034cf8ae7bbc1. / The protective mark of the " +
            "invoice issuer is entered. The protective mark includes 32 characters in the hex" +
            "adecimal notation. Example: 8202f0f963e37a2258b034cf8ae7bbc1.</documentation>\n\t\t" +
            "\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t\t\t\t<length " +
            "value=\"32\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t\t<element nam" +
            "e=\"SubsequentSubmit\" type=\"boolean\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation" +
            ">\n\t\t\t\t\t<documentation>Naknadno posredovani račun je račun, ki je bil izdan brez " +
            "enkratne identifikacijske oznake računa – EOR  (npr. zaradi prekinitve elektrons" +
            "ke povezave z davčnim organom). Vpiše se true, če je račun naknadno posredovan d" +
            "avčnemu organu, drugače false (1 – true, 0 – false). / Subsequently submitted in" +
            "voices are invoices, which have been issued without the unique identification in" +
            "voice mark – EOR (e.g. due to disconnections of electronic connections with the " +
            "tax authority). If the invoice is subsequently submitted to the tax authority, »" +
            "true« is entered, otherwise »false« (1 – true, 0 – false).</documentation>\n\t\t\t\t<" +
            "/annotation>\n\t\t\t</element>\n\t\t\t<element name=\"ReferenceInvoice\" minOccurs=\"0\" max" +
            "Occurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Račun iz elektronske naprav" +
            "e, ki se spreminja.</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<complexType>\n\t\t\t\t\t<se" +
            "quence>\n\t\t\t\t\t\t<element name=\"ReferenceInvoiceIdentifier\" type=\"fu:IdentifierType" +
            "\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše se številka prvotnega računa" +
            " v primeru naknadne spremembe podatkov na prvotnem računu, če je bil prvoten rač" +
            "un izdan preko elektronske naprave. Zavezanec izvaja postopek potrjevanja računo" +
            "v tudi za vse naknadne spremembe podatkov na računu, ki spreminjajo prvoten raču" +
            "n in se nanj nedvoumno nanašajo. Podatek se vpiše v primeru, če se z računom, iz" +
            "danim preko elektronske naprave, spreminja prvoten račun, ki je bil izdan preko " +
            "elektronske naprave. Za vpis številke računa, ki se spreminja, veljajo enaka pra" +
            "vila kot pri vpisu številke računa. Številka računa je sestavljena iz treh delov" +
            ": oznaka poslovnega prostora, oznaka elektronske naprave za izdajanje računov, z" +
            "aporedna številka računa. Številka računa se na računu navede v naslednji obliki" +
            ": oznaka poslovnega prostora-oznaka elektronske naprave-zaporedna številka račun" +
            "a Primer: TRGOVINA1-BLAG2-1234 Podatki se vpisujejo ločeno. / The number of the " +
            "original invoice is entered in cases of subsequent changes of data on the origin" +
            "al invoice if the original invoice has been issued via the electronic device. Th" +
            "e person liable conducts the procedure for verification of invoices also for all" +
            " subsequent changes of data on the invoice, which change the original invoice an" +
            "d they refer to it with reasonable certainty. The data is entered in cases if th" +
            "e original invoice, which has been issued via the electronic device, changes wit" +
            "h the invoice, issued via the electronic device. Rules for entry of the invoice " +
            "number, which is changed, are the same as those for entry of the invoice number." +
            " The invoice number includes three parts: mark of business premises; mark of the" +
            " electronic device for issuing invoices; sequence number of the invoice. The inv" +
            "oice number is stated on the invoice in the following form: mark of business pre" +
            "mises-mark of the electronic device- sequence invoice number. Example: TRGOVINA1" +
            "-BLAG2-1234. Data are entered separately.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t" +
            "\t\t\t\t\t</element>\n\t\t\t\t\t\t<element name=\"ReferenceInvoiceIssueDateTime\" type=\"fu:dat" +
            "eTime\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše se datum in čas izdaje " +
            "prvotnega računa v primeru naknadne spremembe podatkov na prvotnem računu, če je" +
            " bil prvoten račun izdan preko elektronske naprave. Podatek se vpiše v primeru, " +
            "če se z računom, izdanim preko elektronske naprave, spreminja prvoten račun, ki " +
            "je bil izdan preko elektronske naprave. Podatek se vpiše v formatu LLLL-MM-DDTUU" +
            ":MM:SS. / Date and time are entered of issuing the original invoice in cases of " +
            "subsequent changes of data on the original invoice if the original invoice has b" +
            "een issued via the electronic device. The data is entered in cases if the origin" +
            "al invoice, which has been issued via the electronic device, is changed with the" +
            " invoice, issued via the electronic device. The data is entered in the following" +
            " format YYYY-MM-DDTHH:MM:SS.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</elemen" +
            "t>\n\t\t\t\t\t</sequence>\n\t\t\t\t</complexType>\n\t\t\t</element>\n\t\t\t<element name=\"Reference" +
            "SalesBook\" minOccurs=\"0\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>" +
            "Številka računa iz vezane knjige računov, ki se spreminja; številka seta računa " +
            "iz vezane knjige računov, ki se spreminja; serijska številka vezane knjige račun" +
            "ov iz katere je bil izdan račun, ki se spreminja; datum izdaje računa iz vezane " +
            "knjige računov, ki se spreminja. / The number is entered of the issued invoice f" +
            "rom the pre-numbered invoice book, which is changed, if the original invoice has" +
            " been issued from the pre-numbered invoice book; number of the invoice from the " +
            "pre-numbered invoice book, which is changed; number of the invoice set (original" +
            " invoice + its two copies) from the pre-numbered invoice book, which is changed;" +
            " serial number of the pre-numbered invoice book, from which the invoice, which i" +
            "s changed, has been issued; date of issuing the invoice from the pre-numbered in" +
            "voice book, which is changed.</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<complexType" +
            ">\n\t\t\t\t\t<sequence>\n\t\t\t\t\t\t<element name=\"ReferenceSalesBookIdentifier\" type=\"fu:Sa" +
            "lesBookIdentifierType\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Številka raču" +
            "na iz vezane knjige računov, ki se spreminja; številka seta računa iz vezane knj" +
            "ige računov, ki se spreminja; serijska številka vezane knjige računov iz katere " +
            "je bil izdan račun, ki se spreminja. / The number is entered of the issued invoi" +
            "ce from the pre-numbered invoice book, which is changed, if the original invoice" +
            " has been issued from the pre-numbered invoice book; number of the invoice from " +
            "the pre-numbered invoice book, which is changed; number of the invoice set (orig" +
            "inal invoice + its two copies) from the pre-numbered invoice book, which is chan" +
            "ged; serial number of the pre-numbered invoice book, from which the invoice, whi" +
            "ch is changed, has been issued.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</ele" +
            "ment>\n\t\t\t\t\t\t<element name=\"ReferenceSalesBookIssueDate\" type=\"date\">\n\t\t\t\t\t\t\t<ann" +
            "otation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše se datum izdaje prvotnega računa iz vezane" +
            " knjige računov, ki se spreminja, če je bil prvoten račun izdan iz vezane knjige" +
            " računov. Podatek se vpiše v formatu LLLL-MM-DD. Podatek se vpiše v primeru, če " +
            "se z računom, izdanim preko elektronske naprave, spreminja prvoten račun, ki je " +
            "bil izdan iz vezane knjige računov. / The issuing date is entered for the origin" +
            "al invoice from the pre-numbered invoice book, which is changed if the original " +
            "invoice has been issued from the pre-numbered invoice book. The data is entered " +
            "in the following format: YYYY-MM-DD. The data is entered in cases when the origi" +
            "nal invoice, which has been issued from the pre-numbered invoice book, is change" +
            "d with the invoice, issued via the electronic device.</documentation>\n\t\t\t\t\t\t\t</a" +
            "nnotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t</sequence>\n\t\t\t\t</complexType>\n\t\t\t</element>\n\t\t" +
            "\t<element name=\"SpecialNotes\" minOccurs=\"0\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentatio" +
            "n>R_3.20 Vpišejo se morebitne druge oznake, ki podrobneje pojasnjujejo zapise v " +
            "zvezi z vsebino izdanih računov in njihove spremembe. / Potential other marks ar" +
            "e entered, which explain in detail the records in connection with the content of" +
            " invoices issued and their changes.</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpl" +
            "eType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t\t\t\t<minLength value=\"1\"/>\n\t\t\t\t\t\t<maxL" +
            "ength value=\"1000\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t</seq" +
            "uence>\n\t</complexType>\n\t<simpleType name=\"UUIDType\">\n\t\t<annotation>\n\t\t\t<document" +
            "ation>Enkratni identifikator sporočila. Vsako sporočilo mora imeti enkratno iden" +
            "tifikacijsko oznako. Enako velja tudi pri pošiljanju sporočila, ki se zaradi nap" +
            "ake pošilja ponovno. / Unique identifier of the message. Every message shall hav" +
            "e the unique identification mark. The same is valid also for sending messages, w" +
            "hich are resent due to errors.</documentation>\n\t\t</annotation>\n\t\t<restriction ba" +
            "se=\"string\">\n\t\t\t<pattern value=\"[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-" +
            "fA-F0-9]{4}-[a-fA-F0-9]{12}\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<simpleType name" +
            "=\"ClosingTagType\">\n\t\t<annotation>\n\t\t\t<documentation>Zaprtje poslovnega prostora " +
            "/ Closure of business premises</documentation>\n\t\t</annotation>\n\t\t<restriction ba" +
            "se=\"string\">\n\t\t\t<enumeration value=\"Z\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<compl" +
            "exType name=\"HeaderType\">\n\t\t<annotation>\n\t\t\t<documentation>Glava sporočila / Me" +
            "ssage header</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name=\"Mess" +
            "ageID\" type=\"fu:UUIDType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<do" +
            "cumentation>Enkratni identifikator sporočila. Vsako sporočilo mora imeti enkratn" +
            "o identifikacijsko oznako. Enako velja tudi pri pošiljanju sporočila, ki se zara" +
            "di napake pošilja ponovno. / Unique identifier of the message. Every message sha" +
            "ll have the unique identification mark. The same is valid also for sending messa" +
            "ges, which are resent due to errors. </documentation>\n\t\t\t\t</annotation>\n\t\t\t</ele" +
            "ment>\n\t\t\t<element name=\"DateTime\" type=\"fu:dateTime\" minOccurs=\"1\" maxOccurs=\"1\"" +
            ">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Datum in čas pošiljanja sporočila. LLLL-M" +
            "M-DDTUU:MM:SS. / Date and time of sending the message YYYY-MM-DDTHH:MM:SS</docum" +
            "entation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<comple" +
            "xType name=\"HeaderResponseType\">\n\t\t<annotation>\n\t\t\t<documentation>Glava sporočil" +
            "a / Message header</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name" +
            "=\"MessageID\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Identifikator sporočila / Ide" +
            "ntifier of the message</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<" +
            "restriction base=\"string\">\n\t\t\t\t\t\t<minLength value=\"0\"/>\n\t\t\t\t\t\t<maxLength value=\"" +
            "36\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t\t<element name=\"Date" +
            "Time\" type=\"fu:dateTime\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Datum in čas poš" +
            "iljanja sporočila. LLLL-MM-DDTUU:MM:SS. / Date and time of sending the message<" +
            "/documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<" +
            "simpleType name=\"TaxNumberType\">\n\t\t<annotation>\n\t\t\t<documentation>Davčna številk" +
            "a / Tax number</documentation>\n\t\t</annotation>\n\t\t<restriction base=\"positiveInte" +
            "ger\">\n\t\t\t<pattern value=\".{8}\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<simpleType na" +
            "me=\"NumberingStructureType\">\n\t\t<annotation>\n\t\t\t<documentation>Vpiše se oznaka na" +
            "čina dodeljevanja številk računom: C – centralno na nivoju poslovnega prostora, " +
            "B – po posamezni elektronski napravi (blagajna) Oznaka pojasnjuje na kakšen nači" +
            "n se računom dodeljujejo številke. Številke računov se lahko dodeljujejo central" +
            "no na nivoju poslovnega prostora ali posamično na elektronski napravi za izdajan" +
            "je računov. / The mark is entered for the method of assigning numbers to invoice" +
            "s: C - centrally at the level of business premises, B - per individual electroni" +
            "c device (cash register). The mark explains the method for assigning numbers to " +
            "invoices. Invoice numbers may be assigned centrally at the level of business pre" +
            "mises or individually on the electronic device for issuing invoices.</documentat" +
            "ion>\n\t\t</annotation>\n\t\t<restriction base=\"string\">\n\t\t\t<enumeration value=\"B\"/>\n\t" +
            "\t\t<enumeration value=\"C\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<complexType name=\"I" +
            "dentifierType\">\n\t\t<annotation>\n\t\t\t<documentation>Številka računa / Number of the" +
            " invoice</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name=\"Business" +
            "PremiseID\" type=\"fu:BusinessPremiseIDType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<ann" +
            "otation>\n\t\t\t\t\t<documentation>Oznaka poslovnega prostora. Vsebuje lahko samo črke" +
            " in številke: 0-9, a-z, A-Z. / Mark of business premises. It may include only th" +
            "e following letters and numbers: 0-9, a-z, A-Z.</documentation>\n\t\t\t\t</annotation" +
            ">\n\t\t\t</element>\n\t\t\t<element name=\"ElectronicDeviceID\" minOccurs=\"1\" maxOccurs=\"1" +
            "\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Oznaka elektronske naprave. Vsebuje lahk" +
            "o samo črke in številke: 0-9, a-z, A-Z. / Mark of the electronic device. It may " +
            "include only the following letters and numbers: 0-9, a-z, A-Z.</documentation>\n\t" +
            "\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"fu:ElectronicDeviceIDT" +
            "ype\">\n\t\t\t\t\t\t<maxLength value=\"20\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</e" +
            "lement>\n\t\t\t<element name=\"InvoiceNumber\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annot" +
            "ation>\n\t\t\t\t\t<documentation>Zaporedna številka računa. Vsebuje lahko samo števil" +
            "ke 0-9. Niso dovoljene vodilne ničle. / Sequence number of the invoice. It may i" +
            "nclude only numbers 0-9. Zeros cannot be on the first place.</documentation>\n\t\t\t" +
            "\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t\t\t\t<maxLengt" +
            "h value=\"20\"/>\n\t\t\t\t\t\t<minLength value=\"1\"/>\n\t\t\t\t\t\t<pattern value=\"\\d*\"/>\n\t\t\t\t\t</" +
            "restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<com" +
            "plexType name=\"SalesBookIdentifierType\">\n\t\t<annotation>\n\t\t\t<documentation>Števil" +
            "ka računa / Number of the invoice</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t" +
            "\t\t<element name=\"InvoiceNumber\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t" +
            "\t\t\t<documentation>Vpiše se številka računa, izdanega iz vezane knjige računov. /" +
            " The number of the invoice is entered, issued from the pre-numbered invoice book" +
            ".</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"str" +
            "ing\">\n\t\t\t\t\t\t<minLength value=\"1\"/>\n\t\t\t\t\t\t<maxLength value=\"20\"/>\n\t\t\t\t\t</restrict" +
            "ion>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t\t<element name=\"SetNumber\" minOccurs=\"1\" " +
            "maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Številka seta računa iz veza" +
            "ne knjige računov, ki se spreminja / Number of the invoice set (original invoice" +
            " + its two copies) from the pre-numbered invoice book, which is changed.</docume" +
            "ntation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t" +
            "\t\t\t<length value=\"2\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t\t<e" +
            "lement name=\"SerialNumber\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<d" +
            "ocumentation>Vpiše se serijska številka vezane knjige računov iz katere je bil i" +
            "zdan račun, ki se spreminja, če je bil prvoten račun izdan iz vezane knjige raču" +
            "nov. / The serial number is entered of the pre-numbered invoice book, from which" +
            " the invoice, which is changed, has been issued if the original invoice has been" +
            " issued from the pre-numbered invoice book.</documentation>\n\t\t\t\t</annotation>\n\t\t" +
            "\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t\t\t\t<length value=\"12\"/>\n\t\t\t\t\t" +
            "</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<s" +
            "impleType name=\"BusinessPremiseIDType\">\n\t\t<annotation>\n\t\t\t<documentation>Oznaka " +
            "poslovnega prostora / Mark of business premises</documentation>\n\t\t</annotation>\n" +
            "\t\t<restriction base=\"string\">\n\t\t\t<minLength value=\"1\"/>\n\t\t\t<maxLength value=\"20\"" +
            "/>\n\t\t\t<pattern value=\"[0-9a-zA-Z]{1,20}\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<sim" +
            "pleType name=\"ElectronicDeviceIDType\">\n\t\t<annotation>\n\t\t\t<documentation>Oznaka e" +
            "lektronske naprave / Mark of the electronic device</documentation>\n\t\t</annotatio" +
            "n>\n\t\t<restriction base=\"string\">\n\t\t\t<maxLength value=\"20\"/>\n\t\t\t<minLength value=" +
            "\"1\"/>\n\t\t\t<pattern value=\"[0-9a-zA-Z]{1,20}\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<" +
            "simpleType name=\"CustomerVATType\">\n\t\t<annotation>\n\t\t\t<documentation>Davčna števi" +
            "lka oziroma identifikacijska oznaka za namene DDV kupca / Tax number or identifi" +
            "cation mark for VAT purposes of the buyer</documentation>\n\t\t</annotation>\n\t\t<res" +
            "triction base=\"string\">\n\t\t\t<minLength value=\"1\"/>\n\t\t\t<maxLength value=\"20\"/>\n\t\t<" +
            "/restriction>\n\t</simpleType>\n\t<simpleType name=\"TaxRateType\">\n\t\t<annotation>\n\t\t\t" +
            "<documentation>Vrednost davčne stopnje. / Value of the tax rate</documentation>\n" +
            "\t\t</annotation>\n\t\t<restriction base=\"decimal\">\n\t\t\t<totalDigits value=\"7\"/>\n\t\t\t<f" +
            "ractionDigits value=\"2\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<simpleType name=\"Tax" +
            "ableAmountType\">\n\t\t<annotation>\n\t\t\t<documentation>Znesek davčne osnove (po zmanj" +
            "šanju za popuste). / Amount of the tax base (after reduction for discounts)</doc" +
            "umentation>\n\t\t</annotation>\n\t\t<restriction base=\"decimal\">\n\t\t\t<totalDigits value" +
            "=\"16\"/>\n\t\t\t<fractionDigits value=\"2\"/>\n\t\t</restriction>\n\t</simpleType>\n\t<complex" +
            "Type name=\"VATType\">\n\t\t<annotation>\n\t\t\t<documentation>Vpišejo se podatki o DDV. " +
            "/ Data about VAT are entered.</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<e" +
            "lement name=\"TaxRate\" type=\"fu:TaxRateType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<an" +
            "notation>\n\t\t\t\t\t<documentation>Vrednost davčne stopnje. Decimalno ločilo je pika." +
            " / Value of the tax rate. The decimal separator is a dot.</documentation>\n\t\t\t\t</" +
            "annotation>\n\t\t\t</element>\n\t\t\t<element name=\"TaxableAmount\" type=\"fu:TaxableAmoun" +
            "tType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Znesek " +
            "davčne osnove (po zmanjšanju za popuste). Decimalno ločilo je pika. / Amount of " +
            "the tax base (after reduction for discounts). The decimal separator is a dot.</d" +
            "ocumentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"TaxAmount\" type=" +
            "\"fu:TaxAmountType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documenta" +
            "tion>Znesek davka. Decimalno ločilo je pika. / Amount of tax. The decimal separa" +
            "tor is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t</sequence>\n\t</c" +
            "omplexType>\n\t<complexType name=\"FlatRateCompensationType\">\n\t\t<annotation>\n\t\t\t<do" +
            "cumentation>Vpišejo se podatki o pavšalnem nadomestilu. / Data about the flat-ra" +
            "te compensation are entered.</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<el" +
            "ement name=\"FlatRateRate\" type=\"fu:TaxRateType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t" +
            "\t<annotation>\n\t\t\t\t\t<documentation>Vrednost stopnje pavšalnega nadomestila. Decim" +
            "alno ločilo je pika. / Value of the flat-rate compensation\'s rate. The decimal s" +
            "eparator is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element n" +
            "ame=\"FlatRateTaxableAmount\" type=\"fu:TaxableAmountType\" minOccurs=\"1\" maxOccurs=" +
            "\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Osnova oziroma vrednost od katere se o" +
            "bračuna znesek pavšalnega nadomestila (po zmanjšanju za popuste). Decimalno loči" +
            "lo je pika. / The base or value from which the amount of the flat-rate compensat" +
            "ion is settled (after reduction for discounts). The decimal separator is a dot.<" +
            "/documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"FlatRateAmount" +
            "\" type=\"fu:TaxAmountType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<do" +
            "cumentation>Znesek pavšalnega nadomestila. Decimalno ločilo je pika. / Amount of" +
            " the flat-rate compensation. The decimal separator is a dot.</documentation>\n\t\t\t" +
            "\t</annotation>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<complexType name=\"T" +
            "axesPerSellerType\">\n\t\t<annotation>\n\t\t\t<documentation>Vpiše se skupni znesek osta" +
            "lih davkov oziroma dajatev (razen DDV), ki so na računu. / The total amount is e" +
            "ntered of other taxes or duties (except VAT), which are on the invoice.</documen" +
            "tation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name=\"SellerTaxNumber\" type=\"fu" +
            ":TaxNumberType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentatio" +
            "n>Vpiše se davčna številka davčnega zavezanca, v imenu in za račun katerega je b" +
            "il izdan račun, če je račun izdan v tujem imenu in za tuj račun oziroma če je ra" +
            "čun izdal prejemnik računa v imenu in za račun dobavitelja. Če račun ni bil izda" +
            "n v tujem imenu in za tuj račun, se podatek ne vpisuje. / The tax number of the " +
            "taxpayer is entered in the name of and on behalf of whose the invoice has been i" +
            "ssued, if the invoice has been issued in the name of and on behalf of another pe" +
            "rson or if the invoice has been issued by the recipient of the invoice in the na" +
            "me of and on behalf of the supplier. If the invoice has not been issued in the n" +
            "ame of and on behalf of another person, the data is not entered.</documentation>" +
            "\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"VAT\" type=\"fu:VATType\" minOcc" +
            "urs=\"0\" maxOccurs=\"unbounded\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpišejo se p" +
            "odatki o DDV. Podatek se posreduje le, če račun vsebuje znesek obračunanega DDV." +
            " Podatek je sestavljen iz davčne stopnje, davčne osnove in zneska davka. Za davč" +
            "ne stopnje lahko obstaja seznam davčnih stopenj pri davčnemu organu. / Data abou" +
            "t VAT are entered. The data is submitted only if the invoice  includes the amoun" +
            "t of VAT settled. The data consists of the tax rate, tax base and amount of tax." +
            " The tax authority may have a list of tax rates.</d")]
        public string FVI_ManyInvoices {
            get {
                return ((string)(this["FVI_ManyInvoices"]));
            }
            set {
                this["FVI_ManyInvoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<schema xmlns=\"http://www.w3.org/2001/XMLS" +
            "chema\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:ds=\"http://www.w3.org/2" +
            "000/09/xmldsig#\" xmlns:fu=\"http://www.fu.gov.si/\" targetNamespace=\"http://www.fu" +
            ".gov.si/\" elementFormDefault=\"qualified\">\n\t<import namespace=\"http://www.w3.org/" +
            "2000/09/xmldsig#\" schemaLocation=\"http://www.w3.org/TR/2002/REC-xmldsig-core-200" +
            "20212/xmldsig-core-schema.xsd\"/>\n\t<element name=\"InvoiceRequest\">\n\t\t<annotation>" +
            "\n\t\t\t<documentation>Vsebina in oblika sporočila s podatki o računu. / Content a" +
            "nd form of the message with data about the invoice.</documentation>\n\t\t</annotati" +
            "on>\n\t\t<complexType>\n\t\t\t<sequence>\n\t\t\t\t<element name=\"Header\" type=\"fu:HeaderType" +
            "\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t\t<annotation>\n\t\t\t\t\t\t<documentation>Glava spor" +
            "očila / Message header</documentation>\n\t\t\t\t\t</annotation>\n\t\t\t\t</element>\n\t\t\t\t<c" +
            "hoice>\n\t\t\t\t\t<element name=\"Invoice\" type=\"fu:InvoiceType\" minOccurs=\"0\" maxOccur" +
            "s=\"1\">\n\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t<documentation>Vpišejo se podatki o računu, ki " +
            "je izdan z uporabo elektronske naprave. / Data are entered about the invoice, wh" +
            "ich is issued with usage of the electronic device.</documentation>\n\t\t\t\t\t\t</annot" +
            "ation>\n\t\t\t\t\t</element>\n\t\t\t\t\t<element name=\"SalesBookInvoice\" type=\"fu:SalesBookT" +
            "ype\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t<documentation>Vpiše" +
            " se davčna številka zavezanca, ki je izdal račun. / The tax number of the person" +
            " liable, who has issued the invoice, is entered.</documentation>\n\t\t\t\t\t\t</annotat" +
            "ion>\n\t\t\t\t\t</element>\n\t\t\t\t</choice>\n\t\t\t\t<element ref=\"ds:Signature\" minOccurs=\"1\"" +
            " maxOccurs=\"1\"/>\n\t\t\t</sequence>\n\t\t\t<attribute name=\"Id\" type=\"string\">\n\t\t\t\t<anno" +
            "tation>\n\t\t\t\t\t<documentation>Atribut za potrebe digitalnega podpisa. V njem imamo" +
            " id, ki se veže na digitalni podpis. / Attribute for needs of the digital signat" +
            "ure. In it we have id, which is linked to the digital signature.</documentation>" +
            "\n\t\t\t\t</annotation>\n\t\t\t</attribute>\n\t\t</complexType>\n\t</element>\n\t<element name=\"" +
            "InvoiceResponse\">\n\t\t<annotation>\n\t\t\t<documentation>Odgovor za oddajo računa. / " +
            "Response for submitting the invoice.</documentation>\n\t\t</annotation>\n\t\t<complexT" +
            "ype>\n\t\t\t<sequence>\n\t\t\t\t<element name=\"Header\" type=\"fu:HeaderResponseType\"/>\n\t\t\t" +
            "\t<element name=\"UniqueInvoiceID\" type=\"fu:UUIDType\" minOccurs=\"0\">\n\t\t\t\t\t<annotat" +
            "ion>\n\t\t\t\t\t\t<documentation>Enkratni identifikator sporočila. / Unique identifier " +
            "of the message.</documentation>\n\t\t\t\t\t</annotation>\n\t\t\t\t</element>\n\t\t\t\t<element n" +
            "ame=\"Error\" type=\"fu:ErrorType\" minOccurs=\"0\"/>\n\t\t\t\t<element ref=\"ds:Signature\" " +
            "minOccurs=\"0\"/>\n\t\t\t</sequence>\n\t\t\t<attribute name=\"Id\" type=\"string\">\n\t\t\t\t<annot" +
            "ation>\n\t\t\t\t\t<documentation>Atribut za potrebe digitalnega podpisa. V njem imamo " +
            "id, ki se veže na digitalni podpis./ Attribute for needs of the digital signatur" +
            "e. In it we have id, which is linked to the digital signature.</documentation>\n\t" +
            "\t\t\t</annotation>\n\t\t\t</attribute>\n\t\t</complexType>\n\t</element>\n\t<element name=\"Bu" +
            "sinessPremiseRequest\">\n\t\t<annotation>\n\t\t\t<documentation>Vsebina in oblika sporoč" +
            "ila s podatki o poslovnem prostoru zavezanca. / Content and form of the message " +
            "with data about business premises of the person liable.</documentation>\n\t\t</anno" +
            "tation>\n\t\t<complexType>\n\t\t\t<sequence>\n\t\t\t\t<element name=\"Header\" type=\"fu:Header" +
            "Type\" minOccurs=\"1\" maxOccurs=\"1\"/>\n\t\t\t\t<element name=\"BusinessPremise\" type=\"fu" +
            ":BusinessPremiseType\" minOccurs=\"1\" maxOccurs=\"1\"/>\n\t\t\t\t<element ref=\"ds:Signatu" +
            "re\" minOccurs=\"1\" maxOccurs=\"1\"/>\n\t\t\t</sequence>\n\t\t\t<attribute name=\"Id\" type=\"s" +
            "tring\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Atribut za potrebe digitalnega podp" +
            "isa. V njem imamo id, ki se veže na digitalni podpis. / Attribute for needs of t" +
            "he digital signature. In it we have id, which is linked to the digital signature" +
            ".</documentation>\n\t\t\t\t</annotation>\n\t\t\t</attribute>\n\t\t</complexType>\n\t</element>" +
            "\n\t<element name=\"BusinessPremiseResponse\">\n\t\t<annotation>\n\t\t\t<documentation>Odgo" +
            "vor na zahtevo poslovnega prostora. / Response for submitting the business premi" +
            "se.</documentation>\n\t\t</annotation>\n\t\t<complexType>\n\t\t\t<sequence>\n\t\t\t\t<element n" +
            "ame=\"Header\" type=\"fu:HeaderResponseType\"/>\n\t\t\t\t<element name=\"Error\" type=\"fu:E" +
            "rrorType\" minOccurs=\"0\"/>\n\t\t\t\t<element ref=\"ds:Signature\" minOccurs=\"0\" maxOccur" +
            "s=\"1\"/>\n\t\t\t</sequence>\n\t\t\t<attribute name=\"Id\" type=\"string\">\n\t\t\t\t<annotation>\n\t" +
            "\t\t\t\t<documentation>Atribut za potrebe digitalnega podpisa. V njem imamo id, ki s" +
            "e veže na digitalni podpis. / Attribute for needs of the digital signature. In i" +
            "t we have id, which is linked to the digital signature.</documentation>\n\t\t\t\t</an" +
            "notation>\n\t\t\t</attribute>\n\t\t</complexType>\n\t</element>\n\t<complexType name=\"Busin" +
            "essPremiseType\">\n\t\t<annotation>\n\t\t\t<documentation>Poslovni prostor / Business pr" +
            "emises</documentation>\n\t\t</annotation>\n\t\t<sequence>\n\t\t\t<element name=\"TaxNumber\"" +
            " type=\"fu:TaxNumberType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<doc" +
            "umentation>Davčna številka zavezanca, ki izdaja račune / Tax number of the perso" +
            "n liable, who issues invoices</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t" +
            "\t<element name=\"BusinessPremiseID\" type=\"fu:BusinessPremiseIDType\" minOccurs=\"1\"" +
            " maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se oznaka poslovnega " +
            "prostora v katerem zavezanec izdaja račune pri gotovinskem poslovanju. Oznaka je" +
            " lahko sestavljena iz številk in črk 0-9, a-z, A-Z. Oznaka mora biti enaka kot t" +
            "ista, ki je navedena na računih. Oznaka je enkratna na nivoju zavezanca. / The m" +
            "ark is entered of business premises, in which the person liable issues invoices " +
            "in cash operations. The mark may include the following number and letters: 0-9, " +
            "a-z, A-Z. The mark shall be the same as the mark, stated on invoices. The mark i" +
            "s unique at the level of the person liable.</documentation>\n\t\t\t\t</annotation>\n\t\t" +
            "\t</element>\n\t\t\t<element name=\"BPIdentifier\" type=\"fu:BPIdentifierType\" minOccurs" +
            "=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpišejo se podatki o ne" +
            "premičnem ali premičnem poslovnem prostoru. / Data are entered about immovable o" +
            "r movable business premises.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t" +
            "<element name=\"ValidityDate\" type=\"fu:date\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentatio" +
            "n>Datum začetka veljavnosti podatkov o poslovnem prostoru, ki se posredujejo. Po" +
            "datek se vpiše v obliki: LLLL-MM-DD. / The date when data about business premise" +
            "s, which are submitted, become valid. DD / The data is entered in the following " +
            "form: YYYY-MM-DD.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element na" +
            "me=\"ClosingTag\" type=\"fu:ClosingTagType\" minOccurs=\"0\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<d" +
            "ocumentation>Vpiše se podatek o zaprtju poslovnega prostora, če gre za trajno za" +
            "prtje. Možna je vrednost »Z«. Po zaprtju v tem poslovnem prostoru ni več možno i" +
            "zdajati računov in računov z oznako tega poslovnega prostora ni več možno posred" +
            "ovati davčnemu organu. / The data is entered about the closure of business premi" +
            "ses if the closure is permanent. The possible value is »Z«. After closure issuin" +
            "g invoices is not possible anymore in these business premises and it is not poss" +
            "ible to submit invoices to the tax authority with the mark of these business pre" +
            "mises.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"Softwar" +
            "eSupplier\" type=\"fu:SoftwareSupplierType\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t" +
            "\t\t<documentation>Vpiše se podatek o proizvajalcu  ali vzdrževalcu programske opr" +
            "eme za izdajanje računov. Vpiše se eden od podatkov: 1. Davčna številka pravne a" +
            "li fizične osebe / proizvajalca ali vzdrževalca programske opreme s sedežem v Sl" +
            "oveniji  in 2. Naziv in naslov proizvajalca ali vzdrževalca programske opreme, k" +
            "i nima sedeža v Sloveniji. / The data is entered about the producer or software " +
            "maintenance provider for issuing invoices. One of the following data is entered:" +
            " 1. tax number of a legal entity or an individual – producer or software mainten" +
            "ance provider established in Slovenia and 2. title and address of the producer o" +
            "r software maintenance provider not established in Slovenia.</documentation>\n\t\t\t" +
            "\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"SpecialNotes\" minOccurs=\"0\">\n\t\t\t\t" +
            "<annotation>\n\t\t\t\t\t<documentation>Vpišejo se morebitne druge oznake, ki podrobnej" +
            "e pojasnjujejo zapise v zvezi z vsebino podatkov o poslovnem prostoru. / Any oth" +
            "er potential marks are entered, which explain in detail the records in connectio" +
            "n with the content of data about business premises.</documentation>\n\t\t\t\t</annota" +
            "tion>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string\">\n\t\t\t\t\t\t<minLength value=\"" +
            "1\"/>\n\t\t\t\t\t\t<maxLength value=\"1000\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t</simpleType>\n\t\t\t</" +
            "element>\n\t\t</sequence>\n\t</complexType>\n\t<complexType name=\"InvoiceType\">\n\t\t<anno" +
            "tation>\n\t\t\t<documentation>Račun / Invoice</documentation>\n\t\t</annotation>\n\t\t<seq" +
            "uence>\n\t\t\t<element name=\"TaxNumber\" type=\"fu:TaxNumberType\" minOccurs=\"1\" maxOcc" +
            "urs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se davčna številka zavezanca" +
            ", ki je izdal račun. / The tax number of the person liable, who has issued the i" +
            "nvoice, is entered.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element " +
            "name=\"IssueDateTime\" type=\"fu:dateTime\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annota" +
            "tion>\n\t\t\t\t\t<documentation>Vpiše se datum in čas izdaje računa, ki je naveden na " +
            "računu. Podatek se vpiše v formatu LLLL-MM-DDTUU:MM:SS. / Date and time of issui" +
            "ng the invoice, which is stated on the invoice, are entered. The data is entered" +
            " in the following format YYYY-MM-DDTHH:MM:SS.\n</documentation>\n\t\t\t\t</annotation>" +
            "\n\t\t\t</element>\n\t\t\t<element name=\"NumberingStructure\" type=\"fu:NumberingStructure" +
            "Type\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se" +
            " oznaka načina dodeljevanja številk računom: C – centralno na nivoju poslovnega " +
            "prostora, B – po posamezni elektronski napravi (blagajna) Oznaka pojasnjuje na k" +
            "akšen način se računom dodeljujejo številke. Številke računov se lahko dodeljuje" +
            "jo centralno na nivoju poslovnega prostora ali posamično na elektronski napravi " +
            "za izdajanje računov. / The mark is entered for the method of assigning numbers " +
            "to invoices: C - centrally at the level of business premises, B - per individual" +
            " electronic device (cash register). The mark explains the method for assigning n" +
            "umbers to invoices. Invoice numbers may be assigned centrally at the level of bu" +
            "siness premises or individually on the electronic device for issuing invoices.</" +
            "documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"InvoiceIdentifi" +
            "er\" type=\"fu:IdentifierType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t" +
            "<documentation>Vpiše se številka izdanega računa. Vpiše se tudi številka dokumen" +
            "ta, ki spreminja prvotni račun (dobropis, storno,…) v primeru izvajanja postopka" +
            " potrjevanja naknadne spremembe podatkov na računu, ki spreminja prvoten račun i" +
            "n se nanj nedvoumno nanaša. Številka računa je sestavljena iz treh delov: oznaka" +
            " poslovnega prostora; oznaka elektronske naprave za izdajanje računov; zaporedna" +
            " številka računa. Številka računa se na računu navede v naslednji obliki: oznaka" +
            " poslovnega prostora-oznaka elektronske naprave-zaporedna številka računa. Prime" +
            "r: TRGOVINA1-BLAG2-1234 Podatki se vpisujejo ločeno. / The number of the issued " +
            "invoice is entered. The number of the document is also entered, which changes th" +
            "e original invoice (credit, reversing, etc.) in cases of performing the procedur" +
            "e for verification of subsequent changes of data on the invoice, which changes t" +
            "he original invoice and refers to it with reasonable certainty. The invoice numb" +
            "er includes three parts: mark of business premises; mark of the electronic devic" +
            "e for issuing invoices; sequence number of the invoice. The invoice number is st" +
            "ated on the invoice in the following form: mark of business premises-mark of the" +
            " electronic device-sequence invoice number. Example: TRGOVINA1-BLAG2-1234. Data " +
            "are entered separately.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<elem" +
            "ent name=\"CustomerVATNumber\" type=\"fu:CustomerVATType\" minOccurs=\"0\" maxOccurs=\"" +
            "1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se davčna številka oziroma identi" +
            "fikacijska številka za namene DDV kupca oziroma naročnika v primeru, ko so ti po" +
            "datki v skladu z davčnimi predpisi navedeni na računu. Podatek se vpiše, če je n" +
            "aveden na računu. / The tax number is entered or identification number for VAT p" +
            "urposes of the buyer or ordering party in cases when these data are stated on th" +
            "e invoice in accordance with tax regulations.</documentation>\n\t\t\t\t</annotation>\n" +
            "\t\t\t</element>\n\t\t\t<element name=\"InvoiceAmount\" type=\"fu:AmountType\" minOccurs=\"1" +
            "\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vnese se skupni znesek rač" +
            "una. Vpiše se znesek računa skupaj z DDV in ostalimi davki/dajatvami, zmanjšan z" +
            "a zneske popustov. Decimalno ločilo je pika. / The total amount of the invoice i" +
            "s entered. The amount of the invoice is entered together with VAT and other taxe" +
            "s/duties, decreased for amounts of discounts. The decimal separator is a dot.</d" +
            "ocumentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"ReturnsAmount\" t" +
            "ype=\"fu:AmountType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<document" +
            "ation>Vpiše se znesek povračil na računu, ki se priznajo kupcu (npr. na podlagi " +
            "dobropisa za vračilo embalaže). Podatek se vpiše le, če na računu obstajajo povr" +
            "ačila. Decimalno ločilo je pika. / The amount of refunds on the invoice, which a" +
            "re recognized to the buyer (e.g. on the basis of credit for returning packaging)" +
            ", is entered. The data is entered only if there are refunds on the invoice. The " +
            "decimal separator is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<" +
            "element name=\"PaymentAmount\" type=\"fu:AmountType\" minOccurs=\"1\" maxOccurs=\"1\">\n\t" +
            "\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se znesek računa za plačilo. Decimalno" +
            " ločilo je pika. / The amount of the invoice for payment is entered. The decimal" +
            " separator is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element" +
            " name=\"TaxesPerSeller\" type=\"fu:TaxesPerSellerType\" maxOccurs=\"1000\">\n\t\t\t\t<annot" +
            "ation>\n\t\t\t\t\t<documentation>Vpiše se vrednost osnov po vrsti davka ali dajatve, r" +
            "azdeljeno po davčnih stopnjah, in pripadajoči davek ali dajatev, vrednost dobav " +
            "na podlagi posebnih ureditev, dobav pri katerih je plačnik DDV kupec blaga ali n" +
            "aročnik storitve, oproščenih dobav in neobdavčljivih dobav, ločeno po davčnih št" +
            "evilkah davčnih zavezancev. / The value is entered for bases according to types " +
            "of taxes or duties, separated per tax rates, and associated taxes or duties, val" +
            "ue of supplies on the basis of special arrangements, supplies where the payer of" +
            " VAT is the buyer of goods or party ordering services, exempt supplies and non-t" +
            "axable supplies, separated according to tax numbers of taxpayers.</documentation" +
            ">\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"OperatorTaxNumber\" type=\"fu:" +
            "TaxNumberType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation" +
            ">Vpiše še davčna številka fizične osebe (operaterja), ki izda račun z uporabo el" +
            "ektronske naprave za izdajanje računov. V primeru izdaje računa preko samopostre" +
            "žnih elektronskih naprav oziroma ko se račun izda brez prisotnosti fizične osebe" +
            ", se vpiše davčna številka zavezanca. Če oseba nima slovenske davčne številke, s" +
            "e podatek ne vpisuje. / The tax number is entered of the individual (operator), " +
            "who issues the invoice with the usage of the electronic device for issuing invoi" +
            "ces. In cases of issuing invoices via self-service electronic devices or when in" +
            "voices are issued without the presence of individuals, the tax number of the per" +
            "son liable is entered. The data is not entered if the person has no Slovene tax " +
            "number.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"Foreig" +
            "nOperator\" type=\"boolean\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<do" +
            "cumentation>Vpiše se true, če fizična oseba (operater), ki izda račun z uporabo " +
            "elektronske naprave, nima slovenske davčne številke, drugače false (1 - true, 0 " +
            "– false). / You enter »true« if the individual (operator), who issues the invoic" +
            "e with the usage of the electronic device, has no Slovene tax number, otherwise " +
            "»false« (1 – true, 0 – false).</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t" +
            "\t\t<element name=\"ProtectedID\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t" +
            "\t<documentation>Vpiše se zaščitna oznaka izdajatelja računa. Zaščitna oznaka je " +
            "sestavljena iz 32 znakov v heksadecimalnem formatu. Primer: 8202f0f963e37a2258b0" +
            "34cf8ae7bbc1. / The protective mark of the invoice issuer is entered. The protec" +
            "tive mark includes 32 characters in the hexadecimal notation. Example: 8202f0f96" +
            "3e37a2258b034cf8ae7bbc1.</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t" +
            "\t<restriction base=\"string\">\n\t\t\t\t\t\t<length value=\"32\"/>\n\t\t\t\t\t</restriction>\n\t\t\t\t" +
            "</simpleType>\n\t\t\t</element>\n\t\t\t<element name=\"SubsequentSubmit\" type=\"boolean\" m" +
            "inOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Naknadno posred" +
            "ovani račun je račun, ki je bil izdan brez enkratne identifikacijske oznake raču" +
            "na – EOR  (npr. zaradi prekinitve elektronske povezave z davčnim organom). Vpiše" +
            " se true, če je račun naknadno posredovan davčnemu organu, drugače false (1 – tr" +
            "ue, 0 – false). / Subsequently submitted invoices are invoices, which have been " +
            "issued without the unique identification invoice mark – EOR (e.g. due to disconn" +
            "ections of electronic connections with the tax authority). If the invoice is sub" +
            "sequently submitted to the tax authority, »true« is entered, otherwise »false« (" +
            "1 – true, 0 – false).</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<elemen" +
            "t name=\"ReferenceInvoice\" minOccurs=\"0\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t" +
            "<documentation>Račun iz elektronske naprave, ki se spreminja.</documentation>\n\t" +
            "\t\t\t</annotation>\n\t\t\t\t<complexType>\n\t\t\t\t\t<sequence>\n\t\t\t\t\t\t<element name=\"Referenc" +
            "eInvoiceIdentifier\" type=\"fu:IdentifierType\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<docum" +
            "entation>Vpiše se številka prvotnega računa v primeru naknadne spremembe podatko" +
            "v na prvotnem računu, če je bil prvoten račun izdan preko elektronske naprave. Z" +
            "avezanec izvaja postopek potrjevanja računov tudi za vse naknadne spremembe poda" +
            "tkov na računu, ki spreminjajo prvoten račun in se nanj nedvoumno nanašajo. Poda" +
            "tek se vpiše v primeru, če se z računom, izdanim preko elektronske naprave, spre" +
            "minja prvoten račun, ki je bil izdan preko elektronske naprave. Za vpis številke" +
            " računa, ki se spreminja, veljajo enaka pravila kot pri vpisu številke računa. Š" +
            "tevilka računa je sestavljena iz treh delov: oznaka poslovnega prostora, oznaka " +
            "elektronske naprave za izdajanje računov, zaporedna številka računa. Številka ra" +
            "čuna se na računu navede v naslednji obliki: oznaka poslovnega prostora-oznaka e" +
            "lektronske naprave-zaporedna številka računa Primer: TRGOVINA1-BLAG2-1234 Podatk" +
            "i se vpisujejo ločeno. / The number of the original invoice is entered in cases " +
            "of subsequent changes of data on the original invoice if the original invoice ha" +
            "s been issued via the electronic device. The person liable conducts the procedur" +
            "e for verification of invoices also for all subsequent changes of data on the in" +
            "voice, which change the original invoice and they refer to it with reasonable ce" +
            "rtainty. The data is entered in cases if the original invoice, which has been is" +
            "sued via the electronic device, changes with the invoice, issued via the electro" +
            "nic device. Rules for entry of the invoice number, which is changed, are the sam" +
            "e as those for entry of the invoice number. The invoice number includes three pa" +
            "rts: mark of business premises; mark of the electronic device for issuing invoic" +
            "es; sequence number of the invoice. The invoice number is stated on the invoice " +
            "in the following form: mark of business premises-mark of the electronic device- " +
            "sequence invoice number. Example: TRGOVINA1-BLAG2-1234. Data are entered separat" +
            "ely.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t\t<element name=\"" +
            "ReferenceInvoiceIssueDateTime\" type=\"fu:dateTime\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<" +
            "documentation>Vpiše se datum in čas izdaje prvotnega računa v primeru naknadne s" +
            "premembe podatkov na prvotnem računu, če je bil prvoten račun izdan preko elektr" +
            "onske naprave. Podatek se vpiše v primeru, če se z računom, izdanim preko elektr" +
            "onske naprave, spreminja prvoten račun, ki je bil izdan preko elektronske naprav" +
            "e. Podatek se vpiše v formatu LLLL-MM-DDTUU:MM:SS. / Date and time are entered o" +
            "f issuing the original invoice in cases of subsequent changes of data on the ori" +
            "ginal invoice if the original invoice has been issued via the electronic device." +
            " The data is entered in cases if the original invoice, which has been issued via" +
            " the electronic device, is changed with the invoice, issued via the electronic d" +
            "evice. The data is entered in the following format YYYY-MM-DDTHH:MM:SS.</documen" +
            "tation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t</sequence>\n\t\t\t\t</complexType" +
            ">\n\t\t\t</element>\n\t\t\t<element name=\"ReferenceSalesBook\" minOccurs=\"0\" maxOccurs=\"1" +
            "000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Številka računa iz vezane knjige raču" +
            "nov, ki se spreminja; številka seta računa iz vezane knjige računov, ki se sprem" +
            "inja; serijska številka vezane knjige računov iz katere je bil izdan račun, ki s" +
            "e spreminja; datum izdaje računa iz vezane knjige računov, ki se spreminja. / Th" +
            "e number is entered of the issued invoice from the pre-numbered invoice book, wh" +
            "ich is changed, if the original invoice has been issued from the pre-numbered in" +
            "voice book; number of the invoice from the pre-numbered invoice book, which is c" +
            "hanged; number of the invoice set (original invoice + its two copies) from the p" +
            "re-numbered invoice book, which is changed; serial number of the pre-numbered in" +
            "voice book, from which the invoice, which is changed, has been issued; date of i" +
            "ssuing the invoice from the pre-numbered invoice book, which is changed.</docume" +
            "ntation>\n\t\t\t\t</annotation>\n\t\t\t\t<complexType>\n\t\t\t\t\t<sequence>\n\t\t\t\t\t\t<element name" +
            "=\"ReferenceSalesBookIdentifier\" type=\"fu:SalesBookIdentifierType\">\n\t\t\t\t\t\t\t<annot" +
            "ation>\n\t\t\t\t\t\t\t\t<documentation>Številka računa iz vezane knjige računov, ki se sp" +
            "reminja; številka seta računa iz vezane knjige računov, ki se spreminja; serijsk" +
            "a številka vezane knjige računov iz katere je bil izdan račun, ki se spreminja. " +
            "/ The number is entered of the issued invoice from the pre-numbered invoice book" +
            ", which is changed, if the original invoice has been issued from the pre-numbere" +
            "d invoice book; number of the invoice from the pre-numbered invoice book, which " +
            "is changed; number of the invoice set (original invoice + its two copies) from t" +
            "he pre-numbered invoice book, which is changed; serial number of the pre-numbere" +
            "d invoice book, from which the invoice, which is changed, has been issued.</docu" +
            "mentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t\t<element name=\"ReferenceS" +
            "alesBookIssueDate\" type=\"date\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše" +
            " se datum izdaje prvotnega računa iz vezane knjige računov, ki se spreminja, če " +
            "je bil prvoten račun izdan iz vezane knjige računov. Podatek se vpiše v formatu " +
            "LLLL-MM-DD. Podatek se vpiše v primeru, če se z računom, izdanim preko elektrons" +
            "ke naprave, spreminja prvoten račun, ki je bil izdan iz vezane knjige računov. /" +
            " The issuing date is entered for the original invoice from the pre-numbered invo" +
            "ice book, which is changed if the original invoice has been issued from the pre-" +
            "numbered invoice book. The data is entered in the following format: YYYY-MM-DD. " +
            "The data is entered in cases when the original invoice, which has been issued fr" +
            "om the pre-numbered invoice book, is changed with the invoice, issued via the el" +
            "ectronic device.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t</se" +
            "quence>\n\t\t\t\t</complexType>\n\t\t\t</element>\n\t\t\t<element name=\"SpecialNotes\" minOccu" +
            "rs=\"0\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>R_3.20 Vpišejo se morebitne druge o" +
            "znake, ki podrobneje pojasnjujejo zapise v zvezi z vsebino izdanih računov in nj" +
            "ihove spremembe. / Potential other marks are entered, which explain in detail th" +
            "e records in connection with the content of invoices issued and their changes.</" +
            "documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<simpleType>\n\t\t\t\t\t<restriction base=\"string" +
            "\">\n\t\t\t\t\t\t<minLength value=\"1\"/>\n\t\t\t\t\t\t<maxLength value=\"1000\"/>\n\t\t\t\t\t</restricti" +
            "on>\n\t\t\t\t</simpleType>\n\t\t\t</element>\n\t\t</sequence>\n\t</complexType>\n\t<complexType " +
            "name=\"SalesBookType\">\n\t\t<annotation>\n\t\t\t<documentation>Račun – vezana knjiga rač" +
            "unov / Invoice – pre-numbered invoice book</documentation>\n\t\t</annotation>\n\t\t<se" +
            "quence>\n\t\t\t<element name=\"TaxNumber\" type=\"fu:TaxNumberType\" minOccurs=\"1\" maxOc" +
            "curs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se davčna številka zavezanc" +
            "a, ki je izdal račun. / The tax number of the person liable, who has issued the " +
            "invoice, is entered.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element" +
            " name=\"IssueDate\" type=\"fu:date\" minOccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t" +
            "\t\t\t\t<documentation>Vpiše se datum izdaje računa, ki je naveden na računu. Podate" +
            "k se vpiše v formatu LLLL-MM-DD. / The date of issuing the invoice, which is sta" +
            "ted on the invoice, is entered. The data is entered in the following format: YYY" +
            "Y-MM-DD.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"Sales" +
            "BookIdentifier\" type=\"fu:SalesBookIdentifierType\" minOccurs=\"0\">\n\t\t\t\t<annotation" +
            ">\n\t\t\t\t\t<documentation>Vpiše se številka računa, izdanega iz vezane knjige računo" +
            "v.Vpiše se tudi številka dokumenta, ki spreminja prvotni račun (dobropis, storno" +
            ",…), v primeru izvajanja postopka potrjevanja naknadne spremembe podatkov na rač" +
            "unu, ki spreminja prvoten račun in se nanj nedvoumno nanaša. / The number of the" +
            " invoice is entered, issued from the pre-numbered invoice book. The number of th" +
            "e document is also entered, which changes the original invoice (credit, reversin" +
            "g, etc.) in cases of performing the procedure for verification of subsequent cha" +
            "nges of data on the invoice, which changes the original invoice and refers to it" +
            " with reasonable certainty.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<" +
            "element name=\"BusinessPremiseID\" type=\"fu:BusinessPremiseIDType\" minOccurs=\"1\" m" +
            "axOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se oznaka poslovnega pr" +
            "ostora v katerem je bil izdan račun iz vezane knjige računov. Oznaka poslovnega " +
            "prostora mora biti enaka oznaki, ki je bila posredovana v okviru podatkov o posl" +
            "ovnih prostorih. Vsebuje lahko samo črke in številke: 0-9, a-z, A-Z. / The mark " +
            "of business premises is entered, in which the invoice has been issued from the p" +
            "re-numbered invoice book. The mark of business premises shall be the same as the" +
            " mark, which has been submitted within data about business premises. It may incl" +
            "ude only the following letters and numbers: 0-9, a-z, A-Z.</documentation>\n\t\t\t\t<" +
            "/annotation>\n\t\t\t</element>\n\t\t\t<element name=\"CustomerVATNumber\" type=\"fu:Custome" +
            "rVATType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiš" +
            "e se davčna številka oziroma identifikacijska številka za namene DDV kupca oziro" +
            "ma naročnika v primeru, ko so ti podatki v skladu z davčnimi predpisi navedeni n" +
            "a računu. Podatek se vpiše, če je naveden na računu. / The tax number is entered" +
            " or identification number for VAT purposes of the buyer or ordering party in cas" +
            "es when these data are in accordance with tax regulations stated on the invoice." +
            " The data is entered if it is stated on the invoice.\n</documentation>\n\t\t\t\t</anno" +
            "tation>\n\t\t\t</element>\n\t\t\t<element name=\"InvoiceAmount\" type=\"fu:AmountType\" minO" +
            "ccurs=\"1\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vnese se skupni zn" +
            "esek računa. Vpiše se znesek računa skupaj z DDV in ostalimi davki/dajatvami, zm" +
            "anjšan za zneske popustov. Decimalno ločilo je pika. / The total amount of the i" +
            "nvoice is entered. The amount of the invoice is entered together with VAT and ot" +
            "her taxes/duties, decreased for amounts of discounts. The decimal separator is a" +
            " dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"ReturnsA" +
            "mount\" type=\"fu:AmountType\" minOccurs=\"0\" maxOccurs=\"1\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<" +
            "documentation>Vpiše se znesek povračil na računu, ki se priznajo kupcu (npr. na " +
            "podlagi dobropisa za vračilo embalaže). Podatek se vpiše le, če na računu obstaj" +
            "ajo povračila. Decimalno ločilo je pika. / The amount of refunds on the invoice " +
            "is entered, which are recognized to the buyer (e.g. on the credit basis for retu" +
            "rning packaging). The data is entered only if there are refunds on the invoice. " +
            "The decimal separator is a dot.</documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n" +
            "\t\t\t<element name=\"PaymentAmount\" type=\"fu:AmountType\" minOccurs=\"1\" maxOccurs=\"1" +
            "\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Vpiše se znesek računa za plačilo. Decim" +
            "alno ločilo je pika. / The invoice amount for payment is entered. The decimal se" +
            "parator is a dot. </documentation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element n" +
            "ame=\"TaxesPerSeller\" type=\"fu:TaxesPerSellerType\" maxOccurs=\"1000\">\n\t\t\t\t<annotat" +
            "ion>\n\t\t\t\t\t<documentation>Vpiše se vrednost osnov po vrsti davka ali dajatve, raz" +
            "deljeno po davčnih stopnjah, in pripadajoči davek ali dajatev, vrednost dobav na" +
            " podlagi posebnih ureditev, dobav pri katerih je plačnik DDV kupec blaga ali nar" +
            "očnik storitve, oproščenih dobav in neobdavčljivih dobav, ločeno po davčnih štev" +
            "ilkah davčnih zavezancev. / The value of bases is entered according to the type " +
            "of taxes or duties, divided according to tax rates, and associated taxes or duti" +
            "es, value of supplies on the basis of special arrangements, supplies where the p" +
            "ayer of VAT is the buyer of goods or party ordering services, exempt supplies an" +
            "d non-taxable supplies, divided according to tax numbers of taxpayers.</document" +
            "ation>\n\t\t\t\t</annotation>\n\t\t\t</element>\n\t\t\t<element name=\"ReferenceSalesBook\" min" +
            "Occurs=\"0\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Številka račun" +
            "a iz vezane knjige računov, ki se spreminja; številka seta računa iz vezane knji" +
            "ge računov, ki se spreminja; serijska številka vezane knjige računov iz katere j" +
            "e bil izdan račun, ki se spreminja; datum izdaje računa iz vezane knjige računov" +
            ", ki se spreminja. / Number of the invoice from the pre-numbered invoice book, w" +
            "hich is changed; number of the invoice set (original invoice + its two copies) f" +
            "rom the pre-numbered invoice book, which is changed; serial number of the pre-nu" +
            "mbered invoice book, from which the invoice has been issued, which is changed; d" +
            "ate of issuing the invoice from the pre-numbered invoice book, which is changed." +
            "</documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<complexType>\n\t\t\t\t\t<sequence>\n\t\t\t\t\t\t<elem" +
            "ent name=\"ReferenceSalesBookIdentifier\" type=\"fu:SalesBookIdentifierType\">\n\t\t\t\t\t" +
            "\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Številka računa iz vezane knjige računov, " +
            "ki se spreminja; številka seta računa iz vezane knjige računov, ki se spreminja;" +
            " serijska številka vezane knjige računov iz katere je bil izdan račun, ki se spr" +
            "eminja. / Number of the invoice from the pre-numbered invoice book, which is cha" +
            "nged; number of the invoice set (original invoice + its two copies) from the pre" +
            "-numbered invoice book, which is changed; serial number of the pre-numbered invo" +
            "ice book, from which the invoice has been issued, which is changed.</documentati" +
            "on>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n\t\t\t\t\t\t<element name=\"ReferenceSalesBoo" +
            "kIssueDate\" type=\"date\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše se dat" +
            "um izdaje prvotnega računa iz vezane knjige računov, ki se spreminja, če se spre" +
            "minja prvoten račun izdan iz vezane knjige računov. Podatek se vpiše v formatu L" +
            "LLL-MM-DD. Podatek se vpiše v primeru, če se z računom, izdanim iz vezane knjige" +
            " računov, spreminja prvoten račun, ki je bil izdan iz vezane knjige računov. / T" +
            "he date is entered of issuing the original invoice from the pre-numbered invoice" +
            " book, which is changed, if the original invoice is changed issued from the pre-" +
            "numbered invoice book. The data is written in the following format: YYYY-MM-DD. " +
            "The data is entered in cases when the original invoice, which has been issued fr" +
            "om the pre-numbered invoice book, is changed with the invoice, issued from the p" +
            "re-numbered invoice book.</documentation>\n\t\t\t\t\t\t\t</annotation>\n\t\t\t\t\t\t</element>\n" +
            "\t\t\t\t\t</sequence>\n\t\t\t\t</complexType>\n\t\t\t</element>\n\t\t\t<element name=\"ReferenceInv" +
            "oice\" minOccurs=\"0\" maxOccurs=\"1000\">\n\t\t\t\t<annotation>\n\t\t\t\t\t<documentation>Raču" +
            "n iz elektronske naprave, ki se spreminja. / Number of the invoice, issued via t" +
            "he electronic device, which is changed </documentation>\n\t\t\t\t</annotation>\n\t\t\t\t<c" +
            "omplexType>\n\t\t\t\t\t<sequence>\n\t\t\t\t\t\t<element name=\"ReferenceInvoiceIdentifier\" typ" +
            "e=\"fu:IdentifierType\">\n\t\t\t\t\t\t\t<annotation>\n\t\t\t\t\t\t\t\t<documentation>Vpiše se števi" +
            "lka prvotnega računa v")]
        public string FVI_SingleInvoices {
            get {
                return ((string)(this["FVI_SingleInvoices"]));
            }
            set {
                this["FVI_SingleInvoices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns" +
            ":fu=\"http://www.fu.gov.si/\">\n   <soapenv:Header/>\n   <soapenv:Body>\n      <fu:Ec" +
            "hoRequest>test 1</fu:EchoRequest>\n   </soapenv:Body>\n</soapenv:Envelope>")]
        public string FVI_ECHO {
            get {
                return ((string)(this["FVI_ECHO"]));
            }
            set {
                this["FVI_ECHO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Luka\\TestCert\\10329048-1.p12")]
        public string certificateFileName {
            get {
                return ((string)(this["certificateFileName"]));
            }
            set {
                this["certificateFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NVIJCY55TF3L")]
        public string CertPass {
            get {
                return ((string)(this["CertPass"]));
            }
            set {
                this["CertPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://blagajne-test.fu.gov.si:9002/v1/cash_registers")]
        public string fursWebServiceURL {
            get {
                return ((string)(this["fursWebServiceURL"]));
            }
            set {
                this["fursWebServiceURL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.fu.gov.si/")]
        public string fursXmlNamespace {
            get {
                return ((string)(this["fursXmlNamespace"]));
            }
            set {
                this["fursXmlNamespace"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int timeOutInSec {
            get {
                return ((int)(this["timeOutInSec"]));
            }
            set {
                this["timeOutInSec"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DEBUG {
            get {
                return ((bool)(this["DEBUG"]));
            }
            set {
                this["DEBUG"] = value;
            }
        }
    }
}
